import { Level, QuestionItem } from '@/lib/types';

// SRC300 题库 - 基于阅读高频字300字库
// 每道题包含：字形识别(character)、词汇识别(word+meaning)、句子识别(sentence)、理解测试(story)

const questionsSRC300: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: 'SRC300',
    character: '人',
    word: '人们',
    sentence: '公园里有很多人。',
    meaning_question: '"人"的意思是什么？',
    options: ['人物', '动物', '植物'],
    answer: '人物',
    story_text: '人们来到小村子，想找一位神仙。',
    story_question: '人们想找谁？',
    story_options: ['神仙', '国王', '妖怪'],
    story_answer: '神仙',
  },
  {
    level: 'SRC300',
    character: '我',
    word: '我们',
    sentence: '我们是好朋友。',
    meaning_question: '"我"是什么？',
    options: ['自己', '别人', '动物'],
    answer: '自己',
    story_text: '我对好朋友说："我们一起去玩吧！"',
    story_question: '谁想去玩？',
    story_options: ['我', '老师', '爸爸'],
    story_answer: '我',
  },
  {
    level: 'SRC300',
    character: '你',
    word: '你的',
    sentence: '你的书包在哪里？',
    meaning_question: '"你"是指谁？',
    options: ['对方', '自己', '别人'],
    answer: '对方',
    story_text: '你看见那只小猫了吗？它在树下。',
    story_question: '小猫在哪里？',
    story_options: ['树下', '房子里', '水里'],
    story_answer: '树下',
  },
  {
    level: 'SRC300',
    character: '他',
    word: '他们',
    sentence: '他们在学校上课。',
    meaning_question: '"他"是指谁？',
    options: ['另一个男的', '自己', '动物'],
    answer: '另一个男的',
    story_text: '他是勇敢的英雄，帮大家打败了妖怪。',
    story_question: '他是什么样的人？',
    story_options: ['勇敢的英雄', '胆小的人', '坏人'],
    story_answer: '勇敢的英雄',
  },
  {
    level: 'SRC300',
    character: '她',
    word: '她的',
    sentence: '她的名字叫小红。',
    meaning_question: '"她"是指谁？',
    options: ['女的', '男的', '动物'],
    answer: '女的',
    story_text: '她是公主，住在漂亮的城堡里。',
    story_question: '她住在哪里？',
    story_options: ['城堡', '山洞', '森林'],
    story_answer: '城堡',
  },
  {
    level: 'SRC300',
    character: '大',
    word: '大小',
    sentence: '这个苹果很大。',
    meaning_question: '"大"的意思是什么？',
    options: ['很大', '很小', '很多'],
    answer: '很大',
    story_text: '大象用长鼻子喝水。小老鼠在旁边看着。',
    story_question: '谁用鼻子喝水？',
    story_options: ['大象', '小老鼠', '小鸟'],
    story_answer: '大象',
  },
  {
    level: 'SRC300',
    character: '小',
    word: '小鱼',
    sentence: '小鱼在水里游。',
    meaning_question: '"小"的意思是什么？',
    options: ['很小', '很大', '很多'],
    answer: '很小',
    story_text: '小猫在院子里追蝴蝶。蝴蝶飞走了。',
    story_question: '谁在追蝴蝶？',
    story_options: ['小猫', '小狗', '小鸟'],
    story_answer: '小猫',
  },
  {
    level: 'SRC300',
    character: '多',
    word: '很多',
    sentence: '树上有很多苹果。',
    meaning_question: '"多"的意思是什么？',
    options: ['数量大', '很少', '不大'],
    answer: '数量大',
    story_text: '花园里开了很多花，红的黄的都有。',
    story_question: '花园里有什么？',
    story_options: ['很多花', '很多树', '很多石头'],
    story_answer: '很多花',
  },
  {
    level: 'SRC300',
    character: '少',
    word: '少数',
    sentence: '少数人还没有到。',
    meaning_question: '"少"的意思是什么？',
    options: ['数量小', '很大', '很多'],
    answer: '数量小',
    story_text: '草地上只有少数几朵花，其他都是草。',
    story_question: '草地上花多还是少？',
    story_options: ['少', '很多', '数不清'],
    story_answer: '少',
  },
  {
    level: 'SRC300',
    character: '高',
    word: '高山',
    sentence: '那座山很高。',
    meaning_question: '"高"的意思是什么？',
    options: ['从下到上很远', '很矮', '很宽'],
    answer: '从下到上很远',
    story_text: '小明爬上了高山，看见了大海。',
    story_question: '小明看见了什么？',
    story_options: ['大海', '学校', '商店'],
    story_answer: '大海',
  },
  {
    level: 'SRC300',
    character: '低',
    word: '高低',
    sentence: '请把声音放低。',
    meaning_question: '"低"的意思是什么？',
    options: ['不高的', '很大的', '很快的'],
    answer: '不高的',
    story_text: '小鸟飞得很低，快要到地上了。',
    story_question: '小鸟飞得怎么样？',
    story_options: ['很低', '很高', '很快'],
    story_answer: '很低',
  },
  {
    level: 'SRC300',
    character: '长',
    word: '长长',
    sentence: '这条路很长。',
    meaning_question: '"长"的意思是什么？',
    options: ['从一头到另一头很远', '很短', '很宽'],
    answer: '从一头到另一头很远',
    story_text: '蛇有长长的身体，可以在地上爬。',
    story_question: '蛇的身体怎么样？',
    story_options: ['长长的', '短短的', '圆圆的'],
    story_answer: '长长的',
  },
  {
    level: 'SRC300',
    character: '短',
    word: '短小',
    sentence: '这支铅笔很短了。',
    meaning_question: '"短"的意思是什么？',
    options: ['不长的', '很长的', '很粗的'],
    answer: '不长的',
    story_text: '兔子的尾巴很短，猫的尾巴很长。',
    story_question: '谁的尾巴短？',
    story_options: ['兔子', '猫', '狗'],
    story_answer: '兔子',
  },
  {
    level: 'SRC300',
    character: '好',
    word: '好看',
    sentence: '这朵花真好看。',
    meaning_question: '"好"的意思是什么？',
    options: ['不错的', '坏的', '丑的'],
    answer: '不错的',
    story_text: '老师说小红是个好孩子，因为她帮助同学。',
    story_question: '小红为什么是好孩子？',
    story_options: ['帮助同学', '会画画', '跑得快'],
    story_answer: '帮助同学',
  },
  {
    level: 'SRC300',
    character: '新',
    word: '新年',
    sentence: '新年快乐！',
    meaning_question: '"新"的意思是什么？',
    options: ['刚有的', '旧的', '不好的'],
    answer: '刚有的',
    story_text: '新年到了，孩子们穿上新衣服，开心地跑出去玩。',
    story_question: '孩子们穿上什么？',
    story_options: ['新衣服', '旧衣服', '校服'],
    story_answer: '新衣服',
  },
  {
    level: 'SRC300',
    character: '上',
    word: '上面',
    sentence: '书在桌子上。',
    meaning_question: '"上"表示什么？',
    options: ['高的位置', '低的位置', '旁边'],
    answer: '高的位置',
    story_text: '小猫跳上了桌子，把花瓶打翻了。',
    story_question: '花瓶怎么了？',
    story_options: ['被小猫打翻了', '很漂亮', '很大'],
    story_answer: '被小猫打翻了',
  },
  {
    level: 'SRC300',
    character: '下',
    word: '下面',
    sentence: '猫在桌子下面。',
    meaning_question: '"下"表示什么？',
    options: ['低的位置', '高的位置', '旁边'],
    answer: '低的位置',
    story_text: '下雨了，孩子们跑回家躲雨。',
    story_question: '孩子们为什么跑回家？',
    story_options: ['下雨了', '天黑了', '吃饭了'],
    story_answer: '下雨了',
  },
  {
    level: 'SRC300',
    character: '里',
    word: '里面',
    sentence: '房间里面很暖和。',
    meaning_question: '"里"表示什么？',
    options: ['内部', '外部', '旁边'],
    answer: '内部',
    story_text: '山洞里面很黑，但是有宝藏。',
    story_question: '山洞里有什么？',
    story_options: ['宝藏', '太阳', '花'],
    story_answer: '宝藏',
  },
  {
    level: 'SRC300',
    character: '外',
    word: '外面',
    sentence: '外面在下雨。',
    meaning_question: '"外"表示什么？',
    options: ['外部', '内部', '上面'],
    answer: '外部',
    story_text: '外面刮大风了，大树被吹得摇摇晃晃。',
    story_question: '外面怎么了？',
    story_options: ['刮大风', '出太阳', '很安静'],
    story_answer: '刮大风',
  },
  {
    level: 'SRC300',
    character: '天',
    word: '天空',
    sentence: '天空中有白云。',
    meaning_question: '"天"的意思是什么？',
    options: ['头顶上的空间', '地面', '水里'],
    answer: '头顶上的空间',
    story_text: '天上的星星一闪一闪的，月亮又大又圆。',
    story_question: '天上有什么？',
    story_options: ['星星和月亮', '太阳和云', '鸟和飞机'],
    story_answer: '星星和月亮',
  },
  {
    level: 'SRC300',
    character: '山',
    word: '高山',
    sentence: '远处有一座山。',
    meaning_question: '"山"是什么？',
    options: ['很高的大地', '水面', '房子'],
    answer: '很高的大地',
    story_text: '山上长满了树，山下有一条小河。',
    story_question: '山下有什么？',
    story_options: ['小河', '城堡', '学校'],
    story_answer: '小河',
  },
  {
    level: 'SRC300',
    character: '水',
    word: '河水',
    sentence: '河水很清。',
    meaning_question: '"水"是什么？',
    options: ['液体', '固体', '气体'],
    answer: '液体',
    story_text: '小鱼在水里游来游去，开心极了。',
    story_question: '小鱼在哪里游？',
    story_options: ['水里', '天上', '地上'],
    story_answer: '水里',
  },
  {
    level: 'SRC300',
    character: '火',
    word: '火山',
    sentence: '火山会喷火。',
    meaning_question: '"火"是什么？',
    options: ['燃烧的东西', '水', '风'],
    answer: '燃烧的东西',
    story_text: '妈妈用火做饭，好吃极了。但是火很危险，不能碰！',
    story_question: '火能做什么？',
    story_options: ['做饭', '喝水', '飞行'],
    story_answer: '做饭',
  },
  {
    level: 'SRC300',
    character: '风',
    word: '大风',
    sentence: '今天风很大。',
    meaning_question: '"风"是什么？',
    options: ['空气流动', '雨', '云'],
    answer: '空气流动',
    story_text: '大风把小树的叶子都吹走了。',
    story_question: '风把什么吹走了？',
    story_options: ['叶子', '花', '果子'],
    story_answer: '叶子',
  },
  {
    level: 'SRC300',
    character: '云',
    word: '云彩',
    sentence: '天上有白云。',
    meaning_question: '"云"是什么？',
    options: ['天上的白色东西', '地上的草', '水里的鱼'],
    answer: '天上的白色东西',
    story_text: '云彩变成了各种形状，有的像小狗，有的像大山。',
    story_question: '云彩像什么？',
    story_options: ['小狗和大山', '人和树', '鱼和鸟'],
    story_answer: '小狗和大山',
  },
  {
    level: 'SRC300',
    character: '雨',
    word: '下雨',
    sentence: '外面下雨了。',
    meaning_question: '"雨"是什么？',
    options: ['从天上落下的水', '风', '太阳'],
    answer: '从天上落下的水',
    story_text: '下雨了，小青蛙高兴地跳进池塘里。',
    story_question: '谁高兴地跳进池塘？',
    story_options: ['小青蛙', '小猫', '小鸟'],
    story_answer: '小青蛙',
  },
  {
    level: 'SRC300',
    character: '一',
    word: '一个',
    sentence: '桌上有一个苹果。',
    meaning_question: '"一"是什么意思？',
    options: ['数量1', '数量2', '很多'],
    answer: '数量1',
    story_text: '一只小鸟停在树枝上，唱起了歌。',
    story_question: '有几只小鸟？',
    story_options: ['一只', '两只', '三只'],
    story_answer: '一只',
  },
  {
    level: 'SRC300',
    character: '百',
    word: '一百',
    sentence: '这里有一百个孩子。',
    meaning_question: '"百"是什么意思？',
    options: ['数量100', '数量10', '数量1000'],
    answer: '数量100',
    story_text: '村子里有一百个人，大家都是好朋友。',
    story_question: '村子里有多少人？',
    story_options: ['一百个', '十个', '一个'],
    story_answer: '一百个',
  },
  {
    level: 'SRC300',
    character: '来',
    word: '回来',
    sentence: '他回来了。',
    meaning_question: '"来"的意思是什么？',
    options: ['到这里', '离开这里', '待在原地'],
    answer: '到这里',
    story_text: '春天来了，花园里的花都开了。',
    story_question: '花园里的花怎么了？',
    story_options: ['开了', '关了', '飞了'],
    story_answer: '开了',
  },
  {
    level: 'SRC300',
    character: '去',
    word: '出去',
    sentence: '我们去学校。',
    meaning_question: '"去"的意思是什么？',
    options: ['离开这里到这里', '到这里来', '待在原地'],
    answer: '离开这里到这里',
    story_text: '小明去图书馆看书，学到了很多知识。',
    story_question: '小明去了哪里？',
    story_options: ['图书馆', '学校', '商店'],
    story_answer: '图书馆',
  },
  {
    level: 'SRC300',
    character: '看',
    word: '看见',
    sentence: '我看见一只蝴蝶。',
    meaning_question: '"看"的意思是什么？',
    options: ['用眼睛观察', '用耳朵听', '用手摸'],
    answer: '用眼睛观察',
    story_text: '小猴子看见水里的月亮，想把它捞上来。',
    story_question: '小猴子想捞什么？',
    story_options: ['月亮', '太阳', '鱼'],
    story_answer: '月亮',
  },
  {
    level: 'SRC300',
    character: '听',
    word: '听见',
    sentence: '我听见鸟在叫。',
    meaning_question: '"听"的意思是什么？',
    options: ['用耳朵感受声音', '用眼睛看', '用手摸'],
    answer: '用耳朵感受声音',
    story_text: '小白兔听见狼来了，赶紧跑回家躲起来。',
    story_question: '小白兔为什么跑回家？',
    story_options: ['听见狼来了', '听见妈妈叫', '想睡觉'],
    story_answer: '听见狼来了',
  },
  {
    level: 'SRC300',
    character: '说',
    word: '说话',
    sentence: '请大声说话。',
    meaning_question: '"说"的意思是什么？',
    options: ['用嘴表达', '用眼看', '用耳听'],
    answer: '用嘴表达',
    story_text: '老师说话的时候，大家都在认真听。',
    story_question: '大家怎么听老师说话？',
    story_options: ['认真听', '玩闹', '睡觉'],
    story_answer: '认真听',
  },
  {
    level: 'SRC300',
    character: '笑',
    word: '大笑',
    sentence: '妹妹笑得很开心。',
    meaning_question: '"笑"的意思是什么？',
    options: ['高兴的表情', '难过', '生气'],
    answer: '高兴的表情',
    story_text: '小丑表演节目，孩子们大笑起来。',
    story_question: '孩子们为什么大笑？',
    story_options: ['小丑表演节目', '下雨了', '肚子疼'],
    story_answer: '小丑表演节目',
  },
  {
    level: 'SRC300',
    character: '哭',
    word: '哭了',
    sentence: '小宝宝哭了。',
    meaning_question: '"哭"的意思是什么？',
    options: ['难过流眼泪', '高兴', '睡觉'],
    answer: '难过流眼泪',
    story_text: '小女孩找不到妈妈，着急地哭了。',
    story_question: '小女孩为什么哭？',
    story_options: ['找不到妈妈', '想吃东西', '想玩'],
    story_answer: '找不到妈妈',
  },
  {
    level: 'SRC300',
    character: '吃',
    word: '吃饭',
    sentence: '我们吃饭吧。',
    meaning_question: '"吃"的意思是什么？',
    options: ['把食物放进嘴里', '喝水', '睡觉'],
    answer: '把食物放进嘴里',
    story_text: '小兔子在草地上吃草，吃得可开心了。',
    story_question: '小兔子在吃什么？',
    story_options: ['草', '肉', '鱼'],
    story_answer: '草',
  },
  {
    level: 'SRC300',
    character: '跑',
    word: '跑步',
    sentence: '他跑得很快。',
    meaning_question: '"跑"的意思是什么？',
    options: ['快速走', '慢慢走', '站着'],
    answer: '快速走',
    story_text: '小马在草地上跑步，越跑越快。',
    story_question: '小马在做什么？',
    story_options: ['跑步', '睡觉', '喝水'],
    story_answer: '跑步',
  },
  {
    level: 'SRC300',
    character: '跳',
    word: '跳起来',
    sentence: '青蛙跳进水里。',
    meaning_question: '"跳"的意思是什么？',
    options: ['双脚离地弹起', '走', '爬'],
    answer: '双脚离地弹起',
    story_text: '小猴子从这棵树跳到那棵树，开心极了。',
    story_question: '小猴子怎么从一棵树到另一棵树？',
    story_options: ['跳', '走', '飞'],
    story_answer: '跳',
  },
  {
    level: 'SRC300',
    character: '飞',
    word: '飞走',
    sentence: '小鸟飞走了。',
    meaning_question: '"飞"的意思是什么？',
    options: ['在空中移动', '在地上走', '在水里游'],
    answer: '在空中移动',
    story_text: '小鸟张开翅膀飞走了，飞过高山，飞过大海。',
    story_question: '小鸟飞过了什么？',
    story_options: ['高山和大海', '学校', '花园'],
    story_answer: '高山和大海',
  },
  {
    level: 'SRC300',
    character: '找',
    word: '找到',
    sentence: '我找到了钥匙。',
    meaning_question: '"找"的意思是什么？',
    options: ['寻找', '扔掉', '看'],
    answer: '寻找',
    story_text: '小猫找不到妈妈，到处找啊找。终于找到了！',
    story_question: '小猫最后找到了什么？',
    story_options: ['妈妈', '鱼', '玩具'],
    story_answer: '妈妈',
  },
  {
    level: 'SRC300',
    character: '帮',
    word: '帮助',
    sentence: '请帮助我。',
    meaning_question: '"帮"的意思是什么？',
    options: ['协助', '阻碍', '离开'],
    answer: '协助',
    story_text: '大哥哥帮助小妹妹过马路，真勇敢！',
    story_question: '大哥哥帮助谁过马路？',
    story_options: ['小妹妹', '老奶奶', '小狗'],
    story_answer: '小妹妹',
  },
  {
    level: 'SRC300',
    character: '猴',
    word: '猴子',
    sentence: '猴子喜欢吃香蕉。',
    meaning_question: '猴子是什么？',
    options: ['动物', '水果', '汽车'],
    answer: '动物',
    story_text: '小猴子爬上树，摘了一个大桃子。',
    story_question: '小猴子摘了什么？',
    story_options: ['桃子', '香蕉', '苹果'],
    story_answer: '桃子',
  },
  {
    level: 'SRC300',
    character: '鸟',
    word: '小鸟',
    sentence: '小鸟在唱歌。',
    meaning_question: '鸟是什么？',
    options: ['会飞的动物', '鱼', '虫子'],
    answer: '会飞的动物',
    story_text: '小鸟在树上唱歌，歌声真好听。',
    story_question: '小鸟的歌声怎么样？',
    story_options: ['好听', '难听', '很吵'],
    story_answer: '好听',
  },
  {
    level: 'SRC300',
    character: '马',
    word: '小马',
    sentence: '小马在吃草。',
    meaning_question: '马是什么？',
    options: ['动物', '植物', '食物'],
    answer: '动物',
    story_text: '小马过河的时候，不知道水有多深。',
    story_question: '小马在做什么？',
    story_options: ['过河', '爬山', '睡觉'],
    story_answer: '过河',
  },
  {
    level: 'SRC300',
    character: '狗',
    word: '小狗',
    sentence: '小狗在门口。',
    meaning_question: '狗是什么？',
    options: ['动物', '植物', '石头'],
    answer: '动物',
    story_text: '小狗看见主人回来，高兴地摇尾巴。',
    story_question: '小狗为什么摇尾巴？',
    story_options: ['看见主人回来', '想吃东西', '害怕'],
    story_answer: '看见主人回来',
  },
  {
    level: 'SRC300',
    character: '龙',
    word: '龙王',
    sentence: '龙是一种神兽。',
    meaning_question: '龙是什么？',
    options: ['传说中的神兽', '普通的鱼', '一种树'],
    answer: '传说中的神兽',
    story_text: '龙王住在海底的宫殿里，掌管着大海。',
    story_question: '龙王住在哪里？',
    story_options: ['海底', '山上', '天上'],
    story_answer: '海底',
  },
  {
    level: 'SRC300',
    character: '神',
    word: '神仙',
    sentence: '神仙会法术。',
    meaning_question: '"神"在这里的意思是什么？',
    options: ['超自然的存在', '普通人', '动物'],
    answer: '超自然的存在',
    story_text: '神仙帮了穷人，给他变出了一间房子。',
    story_question: '神仙帮了谁？',
    story_options: ['穷人', '国王', '妖怪'],
    story_answer: '穷人',
  },
  {
    level: 'SRC300',
    character: '家',
    word: '回家',
    sentence: '我回家了。',
    meaning_question: '"家"是什么？',
    options: ['住的地方', '学校', '公园'],
    answer: '住的地方',
    story_text: '放学了，小红开开心心地回家。',
    story_question: '小红放学后做什么？',
    story_options: ['回家', '去公园', '去商店'],
    story_answer: '回家',
  },
  {
    level: 'SRC300',
    character: '门',
    word: '打开门',
    sentence: '请关上门。',
    meaning_question: '"门"是什么？',
    options: ['出入口', '窗户', '桌子'],
    answer: '出入口',
    story_text: '有人敲门，妈妈打开门一看，是奶奶来了！',
    story_question: '谁来了？',
    story_options: ['奶奶', '老师', '同学'],
    story_answer: '奶奶',
  },
  {
    level: 'SRC300',
    character: '树',
    word: '大树',
    sentence: '大树下面很凉快。',
    meaning_question: '"树"是什么？',
    options: ['植物', '动物', '石头'],
    answer: '植物',
    story_text: '大树上有一个鸟窝，里面有三只小鸟。',
    story_question: '鸟窝里有什么？',
    story_options: ['三只小鸟', '三颗蛋', '三朵花'],
    story_answer: '三只小鸟',
  },
  {
    level: 'SRC300',
    character: '花',
    word: '花园',
    sentence: '花园里很漂亮。',
    meaning_question: '"花"是什么？',
    options: ['植物开的部分', '动物', '石头'],
    answer: '植物开的部分',
    story_text: '花园里的花开了，有红色的，有黄色的，真漂亮！',
    story_question: '花是什么颜色的？',
    story_options: ['红色和黄色', '蓝色', '黑色'],
    story_answer: '红色和黄色',
  },
  {
    level: 'SRC300',
    character: '河',
    word: '小河',
    sentence: '小河的水很清。',
    meaning_question: '"河"是什么？',
    options: ['流动的水', '山', '路'],
    answer: '流动的水',
    story_text: '小河里有好多鱼，孩子们在河边钓鱼。',
    story_question: '孩子们在做什么？',
    story_options: ['钓鱼', '游泳', '唱歌'],
    story_answer: '钓鱼',
  },
  {
    level: 'SRC300',
    character: '海',
    word: '大海',
    sentence: '大海很蓝。',
    meaning_question: '"海"是什么？',
    options: ['很大很大的水', '小河', '湖'],
    answer: '很大很大的水',
    story_text: '大海里有鲸鱼，鲸鱼是最大的动物。',
    story_question: '大海里有什么？',
    story_options: ['鲸鱼', '老虎', '猴子'],
    story_answer: '鲸鱼',
  },
  {
    level: 'SRC300',
    character: '爱',
    word: '喜欢',
    sentence: '我爱妈妈。',
    meaning_question: '"爱"的意思是什么？',
    options: ['很喜欢', '讨厌', '不关心'],
    answer: '很喜欢',
    story_text: '妈妈爱孩子，每天给他做好吃的饭。',
    story_question: '妈妈怎么爱孩子？',
    story_options: ['做好吃的饭', '买玩具', '讲故事'],
    story_answer: '做好吃的饭',
  },
  {
    level: 'SRC300',
    character: '怕',
    word: '害怕',
    sentence: '我害怕黑暗。',
    meaning_question: '"怕"的意思是什么？',
    options: ['恐惧', '高兴', '生气'],
    answer: '恐惧',
    story_text: '小兔子害怕大灰狼，躲在了树洞里。',
    story_question: '小兔子害怕什么？',
    story_options: ['大灰狼', '小鸟', '蝴蝶'],
    story_answer: '大灰狼',
  },
  {
    level: 'SRC300',
    character: '朋',
    word: '朋友',
    sentence: '你是我的好朋友。',
    meaning_question: '"朋友"是什么意思？',
    options: ['亲近的人', '陌生人', '敌人'],
    answer: '亲近的人',
    story_text: '两个好朋友一起去旅行，路上互相帮助。',
    story_question: '好朋友路上做什么？',
    story_options: ['互相帮助', '吵架', '各走各的'],
    story_answer: '互相帮助',
  },
  {
    level: 'SRC300',
    character: '师',
    word: '老师',
    sentence: '老师教我们读书。',
    meaning_question: '"老师"是什么？',
    options: ['教知识的人', '医生', '警察'],
    answer: '教知识的人',
    story_text: '老师带同学们去花园观察花朵。',
    story_question: '老师带同学们去哪里？',
    story_options: ['花园', '图书馆', '商店'],
    story_answer: '花园',
  },
  {
    level: 'SRC300',
    character: '爸',
    word: '爸爸',
    sentence: '爸爸在看书。',
    meaning_question: '"爸爸"是什么？',
    options: ['父亲', '母亲', '老师'],
    answer: '父亲',
    story_text: '爸爸带我去公园玩，我们一起放风筝。',
    story_question: '爸爸和我在做什么？',
    story_options: ['放风筝', '钓鱼', '跑步'],
    story_answer: '放风筝',
  },
  {
    level: 'SRC300',
    character: '妈',
    word: '妈妈',
    sentence: '妈妈做饭很好吃。',
    meaning_question: '"妈妈"是什么？',
    options: ['母亲', '父亲', '老师'],
    answer: '母亲',
    story_text: '妈妈给我做了一件新衣服，穿上真好看！',
    story_question: '妈妈做了什么？',
    story_options: ['新衣服', '新鞋子', '新书包'],
    story_answer: '新衣服',
  },
  {
    level: 'SRC300',
    character: '国',
    word: '国王',
    sentence: '国王住在城堡里。',
    meaning_question: '"国王"是什么？',
    options: ['国家的领导人', '普通人', '老师'],
    answer: '国家的领导人',
    story_text: '国王把宝物藏在了城堡的密室里，用钥匙锁上门。',
    story_question: '国王用什么锁门？',
    story_options: ['钥匙', '石头', '绳子'],
    story_answer: '钥匙',
  },
  {
    level: 'SRC300',
    character: '英',
    word: '英雄',
    sentence: '他是大英雄。',
    meaning_question: '"英雄"是什么？',
    options: ['勇敢伟大的人', '普通人', '坏人'],
    answer: '勇敢伟大的人',
    story_text: '英雄打败了妖怪，救出了村民。',
    story_question: '英雄救出了谁？',
    story_options: ['村民', '国王', '妖怪'],
    story_answer: '村民',
  },
  {
    level: 'SRC300',
    character: '学',
    word: '学校',
    sentence: '我在学校上学。',
    meaning_question: '"学校"是什么？',
    options: ['学习的地方', '吃饭的地方', '睡觉的地方'],
    answer: '学习的地方',
    story_text: '学校里有很多同学，大家一起学习，一起玩。',
    story_question: '学校里有什么？',
    story_options: ['很多同学', '很多动物', '很多花'],
    story_answer: '很多同学',
  },
  {
    level: 'SRC300',
    character: '城',
    word: '城堡',
    sentence: '城堡很漂亮。',
    meaning_question: '"城堡"是什么？',
    options: ['大的建筑', '小房子', '桥'],
    answer: '大的建筑',
    story_text: '城堡里住着公主，城堡外面有大花园。',
    story_question: '城堡外面有什么？',
    story_options: ['大花园', '大海', '沙漠'],
    story_answer: '大花园',
  },
  {
    level: 'SRC300',
    character: '打',
    word: '打开',
    sentence: '请打开书。',
    meaning_question: '"打开"的意思是什么？',
    options: ['把关着的东西开起来', '关上', '扔掉'],
    answer: '把关着的东西开起来',
    story_text: '小明打开门，看见外面下雪了！',
    story_question: '小明打开门看见什么？',
    story_options: ['下雪了', '出太阳了', '下雨了'],
    story_answer: '下雪了',
  },
  {
    level: 'SRC300',
    character: '变',
    word: '变成',
    sentence: '毛毛虫变成蝴蝶。',
    meaning_question: '"变成"的意思是什么？',
    options: ['改变成为', '保持不变', '消失'],
    answer: '改变成为',
    story_text: '孙悟空变成了一只小鸟，飞上了天空。',
    story_question: '孙悟空变成了什么？',
    story_options: ['小鸟', '大象', '鱼'],
    story_answer: '小鸟',
  },
  {
    level: 'SRC300',
    character: '开',
    word: '开始',
    sentence: '比赛开始了。',
    meaning_question: '"开始"的意思是什么？',
    options: ['起动', '结束', '停止'],
    answer: '起动',
    story_text: '上课铃响了，老师开始讲课。',
    story_question: '什么响了？',
    story_options: ['上课铃', '闹钟', '电话'],
    story_answer: '上课铃',
  },
  {
    level: 'SRC300',
    character: '完',
    word: '完成',
    sentence: '我完成了作业。',
    meaning_question: '"完成"的意思是什么？',
    options: ['做完了', '刚开始', '没做'],
    answer: '做完了',
    story_text: '小明完成了任务，得到了一颗星星。',
    story_question: '小明得到了什么？',
    story_options: ['一颗星星', '一个苹果', '一本书'],
    story_answer: '一颗星星',
  },
];

// 300字库完整字表 - 用于"逐字测试"模式
// 来源：阅读高频字300字库
export const CHAR_LIST_300: string[] = ['人', '我', '你', '他', '她', '它', '大', '小', '多', '少', '高', '低', '长', '短', '好', '坏', '新', '旧', '上', '下', '左', '右', '前', '后', '中', '里', '外', '天', '地', '日', '月', '山', '水', '火', '风', '云', '雨', '东', '西', '南', '北', '一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '百', '千', '万', '来', '去', '回', '进', '出', '开', '关', '有', '没', '是', '不', '会', '能', '要', '想', '给', '把', '和', '在', '从', '到', '这', '那', '谁', '呢', '吗', '吧', '看', '听', '说', '问', '叫', '喊', '笑', '哭', '吃', '喝', '睡', '醒', '坐', '站', '走', '跑', '跳', '飞', '拿', '找', '追', '抓', '推', '拉', '扔', '打', '帮', '救', '藏', '躲', '变', '等', '跟', '学', '教', '做', '爱', '神', '仙', '龙', '猴', '妖', '怪', '魔', '鬼', '鸟', '马', '狗', '猫', '兔', '狼', '家', '门', '窗', '房', '路', '桥', '树', '花', '草', '河', '海', '湖', '城', '村', '塔', '床', '桌', '椅', '灯', '墙', '累', '困', '饿', '冷', '热', '啊', '呀', '哇', '哦', '啦', '嘿', '哈'];

// 300字库完整词表 - 用于"逐字测试"词汇部分
export const WORD_LIST_300: string[] = ['什么', '哪里', '看见', '发现', '听见', '想到', '知道', '记得', '忘记', '打开', '关上', '带走', '回来', '离开', '经过', '变成', '使用', '开始', '继续', '停下', '决定', '试试', '准备', '完成', '保护', '相信', '喜欢', '讨厌', '害怕', '担心', '希望', '孩子', '男孩', '女孩', '朋友', '伙伴', '老师', '同学', '爸爸', '妈妈', '爷爷', '奶奶', '国王', '公主', '王子', '英雄', '师父', '徒弟', '巨人', '小偷', '客人', '主人', '队长', '村长', '国民', '百姓', '山洞', '森林', '学校', '教室', '图书馆', '商店', '市场', '花园', '城堡', '房间', '石头', '天空', '太阳', '月亮', '星星', '云彩', '大海', '高山', '沙漠', '草地', '高兴', '开心', '快乐', '难过', '生气', '紧张', '惊讶', '奇怪', '兴奋', '失望', '勇敢', '聪明', '认真', '善良', '友好', '骄傲', '着急', '舒服', '安全', '为什么', '怎么办', '真的吗', '太好了', '不好了', '快点', '等等', '小心', '别怕', '没关系', '原来', '就是', '当然', '也许', '可能', '一定', '不会', '可以', '不行', '谢谢', '走路', '跑步', '跳起来', '飞走', '说话', '大笑', '哭了', '打开门', '关上门', '找到', '追上', '帮助', '出发', '旅行', '寻找', '宝物', '秘密', '地图', '钥匙', '危险', '怪物', '妖怪', '神仙', '龙王', '魔法', '法术', '任务', '挑战', '胜利', '失败'];

// SRC500 字库 - SRC300 基础 + 西游记主题扩展
export const CHAR_LIST_500: string[] = ["人", "我", "你", "他", "她", "它", "大", "小", "多", "少", "高", "低", "长", "短", "好", "坏", "新", "旧", "上", "下", "左", "右", "前", "后", "中", "里", "外", "天", "地", "日", "月", "山", "水", "火", "风", "云", "雨", "东", "西", "南", "北", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万", "来", "回", "进", "出", "开", "关", "有", "没", "是", "不", "会", "能", "要", "想", "给", "把", "和", "从", "到", "这", "那", "谁", "呢", "吗", "吧", "看", "听", "说", "问", "叫", "喊", "笑", "哭", "吃", "喝", "睡", "醒", "坐", "站", "走", "跑", "跳", "飞", "拿", "找", "追", "抓", "推", "拉", "扔", "打", "帮", "救", "藏", "躲", "变", "等", "跟", "学", "教", "做", "爱", "神", "仙", "龙", "猴", "妖", "怪", "魔", "鸟", "马", "狗", "猫", "兔", "狼", "家", "门", "窗", "房", "路", "桥", "树", "花", "草", "河", "海", "湖", "城", "村", "塔", "床", "桌", "椅", "灯", "墙", "累", "困", "饿", "冷", "热", "呀", "哇", "哦", "啦", "嘿", "哈", "唐", "僧", "悟", "空", "佛", "经", "寺", "庙", "禅", "袈", "裟", "棒", "箍", "筋", "斗", "腾", "驾", "降", "除", "取", "拜", "供", "香", "钟", "鼓", "木", "坛", "禄", "僚", "凤", "麒", "麟", "鹏", "蛟", "蟒", "狐", "蝎", "蛛", "蝠", "龟", "鹤", "鲤", "鲸", "狮", "豹", "猿", "雀", "鸦", "鸽", "鹰", "虎", "鳞", "翼", "爪", "角", "尾", "羽", "巢", "穴", "兽", "骸", "躯", "喙", "卵", "巫", "咒", "杖", "袍", "冠", "徽", "章", "剂", "药", "炉", "镜", "晶", "钻", "戒", "链", "符", "卷", "册", "籍", "隐", "预", "言", "召", "唤", "幻", "影", "魅", "魄", "灵", "魂", "禁", "谜", "阵", "闪", "耀", "咔", "嗖", "呜", "嗡", "探", "索", "迹", "踪", "查", "潜", "伏", "埋", "挖", "闯", "越", "攀", "登", "漂", "航", "驶", "渡", "跨", "穿", "测", "绘", "标", "记", "寻", "觅", "猎", "陷", "避", "绕", "抵", "达", "返", "归", "泊", "岸", "羞", "愧", "孤", "独", "羡", "慕", "嫉", "妒", "焦", "虑", "忐", "忑", "委", "屈", "激", "慰", "敬", "佩", "释", "怨", "恨", "悔", "责", "忠", "诚", "谅", "宽", "毅", "恒", "因", "果", "虽", "然", "但", "且", "即", "若", "则", "否", "并", "既", "仍", "尚", "皆", "故", "至", "亦", "另", "况", "竟", "忽", "顿", "立", "刻", "终", "继", "彻", "底", "究"];

export const WORD_LIST_500: string[] = ["什么", "哪里", "看见", "发现", "听见", "想到", "知道", "记得", "忘记", "打开", "关上", "带走", "回来", "离开", "经过", "变成", "使用", "开始", "继续", "停下", "决定", "试试", "准备", "完成", "保护", "相信", "喜欢", "讨厌", "害怕", "担心", "希望", "孩子", "男孩", "女孩", "朋友", "伙伴", "老师", "同学", "爸爸", "妈妈", "爷爷", "奶奶", "国王", "公主", "王子", "英雄", "师父", "徒弟", "巨人", "小偷", "客人", "主人", "队长", "村长", "国民", "百姓", "山洞", "森林", "学校", "教室", "图书馆", "商店", "市场", "花园", "城堡", "房间", "石头", "天空", "太阳", "月亮", "星星", "云彩", "大海", "高山", "沙漠", "草地", "高兴", "开心", "快乐", "难过", "生气", "紧张", "惊讶", "奇怪", "兴奋", "失望", "勇敢", "聪明", "认真", "善良", "友好", "骄傲", "着急", "舒服", "安全", "为什么", "怎么办", "真的吗", "太好了", "不好了", "快点", "等等", "小心", "别怕", "没关系", "原来", "就是", "当然", "也许", "可能", "一定", "不会", "可以", "不行", "谢谢", "走路", "跑步", "跳起来", "飞走", "说话", "大笑", "哭了", "打开门", "关上门", "找到", "追上", "帮助", "出发", "旅行", "寻找", "宝物", "秘密", "地图", "钥匙", "危险", "怪物", "妖怪", "神仙", "龙王", "魔法", "法术", "任务", "挑战", "胜利", "失败", "唐僧", "悟空", "佛经", "寺庙", "禅房", "袈裟", "木棒", "铁箍", "筋斗", "腾云", "驾雾", "降魔", "除恶", "取经", "拜佛", "供桌", "香炉", "铜钟", "鼓楼", "神坛", "凤凰", "麒麟", "大鹏", "蛟龙", "巨蟒", "狐狸精", "蝎子精", "蜘蛛精", "蝙蝠怪", "仙鹤", "鲸鱼", "雄狮", "猎豹", "翅翼", "利爪", "羽毛", "鸟巢", "洞穴", "神兽", "怪兽", "巫师", "咒语", "魔杖", "长袍", "皇冠", "徽章", "药剂", "药炉", "水晶", "钻石", "戒指", "项链", "符文", "卷轴", "手册", "古籍", "隐身", "预言", "召唤", "幻影", "灵魂", "禁书", "谜团", "法阵", "闪耀", "探索", "线索", "踪迹", "调查", "潜伏", "埋藏", "挖掘", "闯关", "穿越", "攀登", "漂流", "航行", "渡河", "跨海", "测绘", "标记", "寻觅", "猎手", "陷阱", "避险", "抵达", "归航", "靠岸", "羞愧", "孤独", "羡慕", "嫉妒", "焦虑", "忐忑", "委屈", "激动", "安慰", "敬佩", "释然", "怨恨", "后悔", "责任", "忠诚", "原谅", "宽容", "毅力", "恒心", "因为", "结果", "虽然", "但是", "而且", "如果", "否则", "并且", "既然", "仍然", "尚未", "皆可", "因此", "甚至", "另外", "何况", "竟然", "忽然", "顿时", "立刻", "终于", "彻底", "研究"];

// SRC800 字库 - SRC500 基础 + 高级扩展
export const CHAR_LIST_800: string[] = ["人", "我", "你", "他", "她", "它", "大", "小", "多", "少", "高", "低", "长", "短", "好", "坏", "新", "旧", "上", "下", "左", "右", "前", "后", "中", "里", "外", "天", "地", "日", "月", "山", "水", "火", "风", "云", "雨", "东", "西", "南", "北", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万", "来", "回", "进", "出", "开", "关", "有", "没", "是", "不", "会", "能", "要", "想", "给", "把", "和", "从", "到", "这", "那", "谁", "呢", "吗", "吧", "看", "听", "说", "问", "叫", "喊", "笑", "哭", "吃", "喝", "睡", "醒", "坐", "站", "走", "跑", "跳", "飞", "拿", "找", "追", "抓", "推", "拉", "扔", "打", "帮", "救", "藏", "躲", "变", "等", "跟", "学", "教", "做", "爱", "神", "仙", "龙", "猴", "妖", "怪", "魔", "鸟", "马", "狗", "猫", "兔", "狼", "家", "门", "窗", "房", "路", "桥", "树", "花", "草", "河", "海", "湖", "城", "村", "塔", "床", "桌", "椅", "灯", "墙", "累", "困", "饿", "冷", "热", "呀", "哇", "哦", "啦", "嘿", "哈", "唐", "僧", "悟", "空", "佛", "经", "寺", "庙", "禅", "袈", "裟", "棒", "箍", "筋", "斗", "腾", "驾", "降", "除", "取", "拜", "供", "香", "钟", "鼓", "木", "坛", "禄", "僚", "凤", "麒", "麟", "鹏", "蛟", "蟒", "狐", "蝎", "蛛", "蝠", "龟", "鹤", "鲤", "鲸", "狮", "豹", "猿", "雀", "鸦", "鸽", "鹰", "虎", "鳞", "翼", "爪", "角", "尾", "羽", "巢", "穴", "兽", "骸", "躯", "喙", "卵", "巫", "咒", "杖", "袍", "冠", "徽", "章", "剂", "药", "炉", "镜", "晶", "钻", "戒", "链", "符", "卷", "册", "籍", "隐", "预", "言", "召", "唤", "幻", "影", "魅", "魄", "灵", "魂", "禁", "谜", "阵", "闪", "耀", "咔", "嗖", "呜", "嗡", "探", "索", "迹", "踪", "查", "潜", "伏", "埋", "挖", "闯", "越", "攀", "登", "漂", "航", "驶", "渡", "跨", "穿", "测", "绘", "标", "记", "寻", "觅", "猎", "陷", "避", "绕", "抵", "达", "返", "归", "泊", "岸", "羞", "愧", "孤", "独", "羡", "慕", "嫉", "妒", "焦", "虑", "忐", "忑", "委", "屈", "激", "慰", "敬", "佩", "释", "怨", "恨", "悔", "责", "忠", "诚", "谅", "宽", "毅", "恒", "因", "果", "虽", "然", "但", "且", "即", "若", "则", "否", "并", "既", "仍", "尚", "皆", "故", "至", "亦", "另", "况", "竟", "忽", "顿", "立", "刻", "终", "继", "彻", "底", "究", "翰", "墨", "丹", "青", "画", "帖", "碑", "临", "摹", "楷", "隶", "篆", "行", "韵", "律", "诗", "词", "赋", "曲", "乐", "弦", "琴", "瑟", "笛", "箫", "锣", "铃", "铛", "铂", "铄", "铸", "锻", "琢", "磨", "碎", "碧", "翡", "翠", "琼", "瑶", "玛", "瑙", "珊", "瑚", "珍", "珠", "珀", "珩", "琅", "璀", "璨", "崖", "峡", "峭", "峻", "嵘", "嵩", "峦", "嶂", "巍", "峨", "崇", "峥", "涯", "滩", "淀", "淤", "涉", "泅", "汲", "滤", "澄", "澈", "澜", "涟", "漪", "潺", "淙", "淅", "沥", "潇", "湃", "汹", "涌", "涛", "浪", "潮", "汛", "溢", "泛", "沼", "潭", "渊", "穹", "苍", "宇", "宙", "寰", "寥", "廓", "旷", "垠", "疆", "域", "界", "畿", "甸", "郊", "郭", "邑", "郡", "邦", "都", "邻", "邱", "邸"];

export const WORD_LIST_800: string[] = ["什么", "哪里", "看见", "发现", "听见", "想到", "知道", "记得", "忘记", "打开", "关上", "带走", "回来", "离开", "经过", "变成", "使用", "开始", "继续", "停下", "决定", "试试", "准备", "完成", "保护", "相信", "喜欢", "讨厌", "害怕", "担心", "希望", "孩子", "男孩", "女孩", "朋友", "伙伴", "老师", "同学", "爸爸", "妈妈", "爷爷", "奶奶", "国王", "公主", "王子", "英雄", "师父", "徒弟", "巨人", "小偷", "客人", "主人", "队长", "村长", "国民", "百姓", "山洞", "森林", "学校", "教室", "图书馆", "商店", "市场", "花园", "城堡", "房间", "石头", "天空", "太阳", "月亮", "星星", "云彩", "大海", "高山", "沙漠", "草地", "高兴", "开心", "快乐", "难过", "生气", "紧张", "惊讶", "奇怪", "兴奋", "失望", "勇敢", "聪明", "认真", "善良", "友好", "骄傲", "着急", "舒服", "安全", "为什么", "怎么办", "真的吗", "太好了", "不好了", "快点", "等等", "小心", "别怕", "没关系", "原来", "就是", "当然", "也许", "可能", "一定", "不会", "可以", "不行", "谢谢", "走路", "跑步", "跳起来", "飞走", "说话", "大笑", "哭了", "打开门", "关上门", "找到", "追上", "帮助", "出发", "旅行", "寻找", "宝物", "秘密", "地图", "钥匙", "危险", "怪物", "妖怪", "神仙", "龙王", "魔法", "法术", "任务", "挑战", "胜利", "失败", "唐僧", "悟空", "佛经", "寺庙", "禅房", "袈裟", "木棒", "铁箍", "筋斗", "腾云", "驾雾", "降魔", "除恶", "取经", "拜佛", "供桌", "香炉", "铜钟", "鼓楼", "神坛", "凤凰", "麒麟", "大鹏", "蛟龙", "巨蟒", "狐狸精", "蝎子精", "蜘蛛精", "蝙蝠怪", "仙鹤", "鲸鱼", "雄狮", "猎豹", "翅翼", "利爪", "羽毛", "鸟巢", "洞穴", "神兽", "怪兽", "巫师", "咒语", "魔杖", "长袍", "皇冠", "徽章", "药剂", "药炉", "水晶", "钻石", "戒指", "项链", "符文", "卷轴", "手册", "古籍", "隐身", "预言", "召唤", "幻影", "灵魂", "禁书", "谜团", "法阵", "闪耀", "探索", "线索", "踪迹", "调查", "潜伏", "埋藏", "挖掘", "闯关", "穿越", "攀登", "漂流", "航行", "渡河", "跨海", "测绘", "标记", "寻觅", "猎手", "陷阱", "避险", "抵达", "归航", "靠岸", "羞愧", "孤独", "羡慕", "嫉妒", "焦虑", "忐忑", "委屈", "激动", "安慰", "敬佩", "释然", "怨恨", "后悔", "责任", "忠诚", "原谅", "宽容", "毅力", "恒心", "因为", "结果", "虽然", "但是", "而且", "如果", "否则", "并且", "既然", "仍然", "尚未", "皆可", "因此", "甚至", "另外", "何况", "竟然", "忽然", "顿时", "立刻", "终于", "彻底", "研究", "翰墨", "丹青", "绘画", "字帖", "碑文", "临摹", "楷书", "隶书", "篆书", "行书", "草书", "韵律", "诗词", "赋曲", "乐章", "琴弦", "笛箫", "铜锣", "铃铛", "雕刻", "锻造", "琢磨", "碎石", "翡翠", "琼瑶", "玛瑙", "珊瑚", "珍珠", "琥珀", "悬崖", "峡谷", "陡峭", "险峻", "巍峨", "崇山", "汹涌", "波涛", "海浪", "潮汐", "汛期", "沼泽", "深渊", "天穹", "苍穹", "宇宙", "寰宇", "辽阔", "边疆", "疆域", "界限", "郊外", "邦国", "都城", "邻邦", "峻岭", "峭壁", "飞瀑", "潺潺", "淙淙", "淅沥", "潇洒", "汹涌澎湃", "浩瀚", "辽远", "广袤", "磅礴", "气势恢宏", "雄伟壮丽", "山清水秀", "鸟语花香", "莺歌燕舞", "春暖花开", "秋高气爽", "冰天雪地", "风和日丽", "万里无云", "碧空如洗", "层峦叠嶂", "崇山峻岭", "悬崖峭壁", "飞流直下", "波澜壮阔", "浩浩荡荡", "气吞山河", "惊涛骇浪", "翻江倒海", "排山倒海", "风起云涌", "电闪雷鸣", "狂风暴雨", "和风细雨", "春风化雨", "拨云见日", "豁然开朗", "豁达", "超然", "物外", "逍遥", "自在", "悠然", "夙愿", "宿愿", "期盼", "渴望", "向往", "憧憬", "祈盼", "祈祷", "祝福", "庇佑", "护佑", "恩泽", "恩惠", "浩荡", "浩渺", "渺茫", "苍茫", "茫茫", "广阔", "开阔", "壮阔", "壮丽", "壮观", "奇观", "奇景", "奇迹", "神奇", "奇妙", "美妙", "绝妙", "巧妙", "奇巧", "精巧", "精致", "精美", "精湛", "精深", "渊博", "渊深", "深邃", "深奥", "浅显", "通俗", "易懂", "浅易", "简易", "简明", "简洁", "简练", "精练", "凝练", "洗练", "纯熟", "熟练", "娴熟", "老练", "稳练", "稳健", "稳妥", "稳重", "沉稳", "沉着", "镇定", "镇静", "从容", "泰然", "安然", "平安"];

// SRC500 题库 - 西游记主题扩展
const questionsSRC500: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: "SRC500",
    character: "唐",
    word: "唐僧",
    sentence: "唐僧去西天取经。",
    meaning_question: "\"唐\"在这里指什么？",
    options: ["朝代名", "方向", "颜色"],
    answer: "朝代名",
    story_text: "唐僧带着三个徒弟去西天取经，路上遇到了很多妖怪。",
    story_question: "唐僧要去哪里？",
    story_options: ["西天", "东海", "南山"],
    story_answer: "西天",
  },
  {
    level: "SRC500",
    character: "悟",
    word: "悟空",
    sentence: "悟空本领很大。",
    meaning_question: "\"悟\"的意思是什么？",
    options: ["明白", "睡觉", "吃饭"],
    answer: "明白",
    story_text: "孙悟空悟出了七十二变的秘诀，可以变成任何东西。",
    story_question: "孙悟空悟出了什么？",
    story_options: ["七十二变", "筋斗云", "金箍棒"],
    story_answer: "七十二变",
  },
  {
    level: "SRC500",
    character: "空",
    word: "空中",
    sentence: "鸟在空中飞。",
    meaning_question: "\"空\"的意思是什么？",
    options: ["天空", "地面", "水里"],
    answer: "天空",
    story_text: "孙悟空在空中翻筋斗云，一翻就是十万八千里。",
    story_question: "孙悟空怎么飞？",
    story_options: ["翻筋斗云", "走路", "骑马"],
    story_answer: "翻筋斗云",
  },
  {
    level: "SRC500",
    character: "佛",
    word: "佛经",
    sentence: "他天天读佛经。",
    meaning_question: "\"佛\"是什么？",
    options: ["一种信仰", "动物", "食物"],
    answer: "一种信仰",
    story_text: "佛祖住在灵山上，唐僧历经千辛万苦终于见到了佛祖。",
    story_question: "佛祖住在哪里？",
    story_options: ["灵山", "天宫", "龙宫"],
    story_answer: "灵山",
  },
  {
    level: "SRC500",
    character: "经",
    word: "取经",
    sentence: "他们去取经。",
    meaning_question: "\"经\"在这里指什么？",
    options: ["佛经", "经常", "经过"],
    answer: "佛经",
    story_text: "取经的路上有九九八十一难，唐僧师徒一一克服了。",
    story_question: "取经路上有多少难？",
    story_options: ["八十一难", "十难", "一百难"],
    story_answer: "八十一难",
  },
  {
    level: "SRC500",
    character: "寺",
    word: "寺庙",
    sentence: "山上有一座寺庙。",
    meaning_question: "\"寺\"是什么？",
    options: ["宗教建筑", "学校", "商店"],
    answer: "宗教建筑",
    story_text: "寺庙里住着和尚，每天敲钟念经。",
    story_question: "寺庙里住着谁？",
    story_options: ["和尚", "学生", "商人"],
    story_answer: "和尚",
  },
  {
    level: "SRC500",
    character: "香",
    word: "香炉",
    sentence: "香炉里冒着烟。",
    meaning_question: "\"香\"是什么？",
    options: ["有香味的东西", "颜色", "声音"],
    answer: "有香味的东西",
    story_text: "供桌上摆着香炉，人们烧香拜佛。",
    story_question: "人们在供桌前做什么？",
    story_options: ["烧香拜佛", "吃饭", "睡觉"],
    story_answer: "烧香拜佛",
  },
  {
    level: "SRC500",
    character: "凤",
    word: "凤凰",
    sentence: "凤凰是神鸟。",
    meaning_question: "\"凤\"是什么？",
    options: ["传说中的神鸟", "普通鸟", "昆虫"],
    answer: "传说中的神鸟",
    story_text: "凤凰从火焰中重生，羽毛五彩斑斓。",
    story_question: "凤凰从什么中重生？",
    story_options: ["火焰", "水里", "土里"],
    story_answer: "火焰",
  },
  {
    level: "SRC500",
    character: "虎",
    word: "老虎",
    sentence: "老虎很凶猛。",
    meaning_question: "\"虎\"是什么？",
    options: ["猛兽", "小虫", "鱼"],
    answer: "猛兽",
    story_text: "老虎是森林之王，额头上有个\"王\"字。",
    story_question: "老虎额头有什么？",
    story_options: ["王字", "花纹", "疤痕"],
    story_answer: "王字",
  },
  {
    level: "SRC500",
    character: "药",
    word: "药炉",
    sentence: "药炉在烧着。",
    meaning_question: "\"药\"是什么？",
    options: ["治病的", "吃的", "玩的"],
    answer: "治病的",
    story_text: "太上老君在药炉里炼出了仙丹。",
    story_question: "太上老君炼出了什么？",
    story_options: ["仙丹", "食物", "衣服"],
    story_answer: "仙丹",
  },
  {
    level: "SRC500",
    character: "镜",
    word: "镜子",
    sentence: "镜子里有自己。",
    meaning_question: "\"镜\"是什么？",
    options: ["照影子的", "吃的", "穿的"],
    answer: "照影子的",
    story_text: "照妖镜能照出妖怪的真面目。",
    story_question: "照妖镜能做什么？",
    story_options: ["照出妖怪真面目", "照出未来", "照出过去"],
    story_answer: "照出妖怪真面目",
  },
  {
    level: "SRC500",
    character: "钻",
    word: "钻石",
    sentence: "钻石很亮。",
    meaning_question: "\"钻\"是什么？",
    options: ["珍贵石头", "普通石头", "泥土"],
    answer: "珍贵石头",
    story_text: "孙悟空的钻地术可以钻入地下。",
    story_question: "孙悟空的钻地术可以做什么？",
    story_options: ["钻入地下", "飞上天", "游泳"],
    story_answer: "钻入地下",
  },
  {
    level: "SRC500",
    character: "魂",
    word: "灵魂",
    sentence: "灵魂不灭。",
    meaning_question: "\"魂\"是什么？",
    options: ["精神", "身体", "衣服"],
    answer: "精神",
    story_text: "妖怪把人的灵魂吸走了，只有打败妖怪才能救回来。",
    story_question: "怎么救回灵魂？",
    story_options: ["打败妖怪", "逃跑", "哭"],
    story_answer: "打败妖怪",
  },
  {
    level: "SRC500",
    character: "探",
    word: "探索",
    sentence: "他们去探索。",
    meaning_question: "\"探\"的意思是什么？",
    options: ["寻找", "逃跑", "睡觉"],
    answer: "寻找",
    story_text: "探险家深入山洞探索，发现了一幅古画。",
    story_question: "探险家发现了什么？",
    story_options: ["古画", "金币", "水源"],
    story_answer: "古画",
  },
  {
    level: "SRC500",
    character: "埋",
    word: "埋藏",
    sentence: "宝物埋在地下。",
    meaning_question: "\"埋\"的意思是什么？",
    options: ["藏在地下", "拿出来", "扔掉"],
    answer: "藏在地下",
    story_text: "海盗把宝物埋藏在一个小岛上，画了一张藏宝图。",
    story_question: "海盗把宝物藏在哪里？",
    story_options: ["小岛上", "山洞里", "水里"],
    story_answer: "小岛上",
  },
  {
    level: "SRC500",
    character: "勇",
    word: "勇敢",
    sentence: "他很勇敢。",
    meaning_question: "\"勇\"的意思是什么？",
    options: ["有勇气", "害怕", "退缩"],
    answer: "有勇气",
    story_text: "面对凶猛的蛟龙，勇士毫不退缩。",
    story_question: "勇士面对蛟龙怎么做？",
    story_options: ["毫不退缩", "转身逃跑", "躲起来"],
    story_answer: "毫不退缩",
  },
  {
    level: "SRC500",
    character: "忠",
    word: "忠诚",
    sentence: "他对朋友很忠诚。",
    meaning_question: "\"忠\"的意思是什么？",
    options: ["忠心", "背叛", "离开"],
    answer: "忠心",
    story_text: "忠诚的猎犬一直守护着主人，从不离开。",
    story_question: "猎犬怎么守护主人？",
    story_options: ["从不离开", "经常离开", "偶尔离开"],
    story_answer: "从不离开",
  },
  {
    level: "SRC500",
    character: "宽",
    word: "宽容",
    sentence: "要学会宽容。",
    meaning_question: "\"宽\"的意思是什么？",
    options: ["心胸大", "狭窄", "生气"],
    answer: "心胸大",
    story_text: "宽容别人就是善待自己，原谅别人的错误。",
    story_question: "宽容别人等于什么？",
    story_options: ["善待自己", "惩罚自己", "放弃自己"],
    story_answer: "善待自己",
  },
  {
    level: "SRC500",
    character: "毅",
    word: "毅力",
    sentence: "他有很强的毅力。",
    meaning_question: "\"毅\"的意思是什么？",
    options: ["坚持不懈", "放弃", "犹豫"],
    answer: "坚持不懈",
    story_text: "小蜗牛凭着毅力终于爬上了高高的城墙。",
    story_question: "小蜗牛靠什么爬上城墙？",
    story_options: ["毅力", "翅膀", "风"],
    story_answer: "毅力",
  },
  {
    level: "SRC500",
    character: "果",
    word: "结果",
    sentence: "种瓜得瓜，结果很好。",
    meaning_question: "\"果\"的意思是什么？",
    options: ["结局", "开始", "中间"],
    answer: "结局",
    story_text: "因为下雨了，所以路上很滑。",
    story_question: "为什么路上滑？",
    story_options: ["下雨了", "下雪了", "出太阳了"],
    story_answer: "下雨了",
  },
];

// SRC800 题库 - 高级文化扩展
const questionsSRC800: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: "SRC800",
    character: "翰",
    word: "翰墨",
    sentence: "翰墨飘香。",
    meaning_question: "\"翰\"在这里指什么？",
    options: ["书法", "食物", "动物"],
    answer: "书法",
    story_text: "翰墨丹青是中国传统文化中的瑰宝，书法和绘画相辅相成。",
    story_question: "翰墨丹青指的是什么？",
    story_options: ["书法和绘画", "音乐和舞蹈", "诗歌和散文"],
    story_answer: "书法和绘画",
  },
  {
    level: "SRC800",
    character: "丹",
    word: "丹青",
    sentence: "丹青色彩斑斓。",
    meaning_question: "\"丹青\"指什么？",
    options: ["绘画", "草药", "燃料"],
    answer: "绘画",
    story_text: "丹青妙手画的山水画栩栩如生，如同真景。",
    story_question: "丹青妙手指什么人？",
    story_options: ["画家", "医生", "工匠"],
    story_answer: "画家",
  },
  {
    level: "SRC800",
    character: "诗",
    word: "诗词",
    sentence: "唐诗很有名。",
    meaning_question: "\"诗\"是什么？",
    options: ["韵文", "故事", "信"],
    answer: "韵文",
    story_text: "李白是唐朝的大诗人，他的诗词流传千古。",
    story_question: "李白是什么人？",
    story_options: ["大诗人", "大将", "皇帝"],
    story_answer: "大诗人",
  },
  {
    level: "SRC800",
    character: "琴",
    word: "琴弦",
    sentence: "琴声悠扬。",
    meaning_question: "\"琴\"是什么？",
    options: ["乐器", "工具", "武器"],
    answer: "乐器",
    story_text: "伯牙弹琴，钟子期能听懂他弹的是高山还是流水。",
    story_question: "谁能听懂伯牙的琴声？",
    story_options: ["钟子期", "路人", "皇帝"],
    story_answer: "钟子期",
  },
  {
    level: "SRC800",
    character: "碧",
    word: "碧空",
    sentence: "碧空如洗。",
    meaning_question: "\"碧\"是什么颜色？",
    options: ["青绿色", "红色", "黑色"],
    answer: "青绿色",
    story_text: "碧空万里无云，天空蓝得像宝石一样。",
    story_question: "天空蓝得像什么？",
    story_options: ["宝石", "黄金", "白银"],
    story_answer: "宝石",
  },
  {
    level: "SRC800",
    character: "崖",
    word: "悬崖",
    sentence: "悬崖很陡峭。",
    meaning_question: "\"崖\"是什么？",
    options: ["陡峭的山壁", "平地", "河流"],
    answer: "陡峭的山壁",
    story_text: "悬崖上长着一棵松树，风雨不倒。",
    story_question: "悬崖上长着什么？",
    story_options: ["松树", "花朵", "草"],
    story_answer: "松树",
  },
  {
    level: "SRC800",
    character: "潮",
    word: "海潮",
    sentence: "海潮涨了。",
    meaning_question: "\"潮\"是什么？",
    options: ["涨落的水", "风", "云"],
    answer: "涨落的水",
    story_text: "钱塘江的大潮汹涌澎湃，壮观极了。",
    story_question: "钱塘江大潮怎么样？",
    story_options: ["汹涌澎湃", "平静", "很小"],
    story_answer: "汹涌澎湃",
  },
  {
    level: "SRC800",
    character: "穹",
    word: "苍穹",
    sentence: "苍穹无边。",
    meaning_question: "\"穹\"指什么？",
    options: ["天空", "大地", "海洋"],
    answer: "天空",
    story_text: "望着苍穹，繁星点点，宇宙无穷无尽。",
    story_question: "苍穹中有什么？",
    story_options: ["繁星", "太阳", "月亮"],
    story_answer: "繁星",
  },
  {
    level: "SRC800",
    character: "壮",
    word: "壮观",
    sentence: "景色很壮观。",
    meaning_question: "\"壮\"的意思是什么？",
    options: ["雄伟", "弱小", "普通"],
    answer: "雄伟",
    story_text: "万里长城雄伟壮观，是世界上最长的城墙。",
    story_question: "万里长城怎么样？",
    story_options: ["雄伟壮观", "矮小", "破旧"],
    story_answer: "雄伟壮观",
  },
  {
    level: "SRC800",
    character: "奥",
    word: "深奥",
    sentence: "道理很深奥。",
    meaning_question: "\"奥\"的意思是什么？",
    options: ["深刻", "简单", "浅显"],
    answer: "深刻",
    story_text: "宇宙的奥秘深奥莫测，科学家不断探索。",
    story_question: "谁在探索宇宙奥秘？",
    story_options: ["科学家", "农民", "商人"],
    story_answer: "科学家",
  },
  {
    level: "SRC800",
    character: "稳",
    word: "稳健",
    sentence: "步伐稳健。",
    meaning_question: "\"稳\"的意思是什么？",
    options: ["安定", "摇晃", "快速"],
    answer: "安定",
    story_text: "老将军稳健地指挥军队，不慌不忙。",
    story_question: "老将军怎么指挥军队？",
    story_options: ["稳健", "慌张", "快速"],
    story_answer: "稳健",
  },
  {
    level: "SRC800",
    character: "泰",
    word: "泰然",
    sentence: "泰然自若。",
    meaning_question: "\"泰\"的意思是什么？",
    options: ["安定", "惊慌", "愤怒"],
    answer: "安定",
    story_text: "面对危险，他泰然自若，冷静地想出了办法。",
    story_question: "他面对危险怎么样？",
    story_options: ["泰然自若", "惊慌失措", "逃跑"],
    story_answer: "泰然自若",
  },
  {
    level: "SRC800",
    character: "豁",
    word: "豁然",
    sentence: "豁然开朗。",
    meaning_question: "\"豁\"的意思是什么？",
    options: ["开阔", "狭窄", "黑暗"],
    answer: "开阔",
    story_text: "走出山洞，眼前豁然开朗，一片美丽的花海。",
    story_question: "走出山洞看到了什么？",
    story_options: ["花海", "沙漠", "大海"],
    story_answer: "花海",
  },
  {
    level: "SRC800",
    character: "磅",
    word: "磅礴",
    sentence: "气势磅礴。",
    meaning_question: "\"磅礴\"的意思是什么？",
    options: ["盛大", "微弱", "平静"],
    answer: "盛大",
    story_text: "黄河气势磅礴地奔流入海，波澜壮阔。",
    story_question: "黄河怎么奔流入海？",
    story_options: ["气势磅礴", "缓慢", "安静"],
    story_answer: "气势磅礴",
  },
  {
    level: "SRC800",
    character: "韧",
    word: "坚韧",
    sentence: "坚韧不拔。",
    meaning_question: "\"韧\"的意思是什么？",
    options: ["有韧性", "脆弱", "柔软"],
    answer: "有韧性",
    story_text: "竹子坚韧不拔，任凭风吹雨打也不折断。",
    story_question: "竹子怎么样？",
    story_options: ["坚韧不拔", "容易折断", "柔软无力"],
    story_answer: "坚韧不拔",
  },
  {
    level: "SRC800",
    character: "幽",
    word: "幽默",
    sentence: "他很幽默。",
    meaning_question: "\"幽\"的意思是什么？",
    options: ["有趣", "害怕", "生气"],
    answer: "有趣",
    story_text: "他幽默风趣，说的话引得大家哈哈大笑。",
    story_question: "他的话怎么样？",
    story_options: ["引得大笑", "让人难过", "让人生气"],
    story_answer: "引得大笑",
  },
  {
    level: "SRC800",
    character: "禅",
    word: "禅宗",
    sentence: "禅宗沉静。",
    meaning_question: "\"禅\"的意思是什么？",
    options: ["安静", "吵闹", "忙乱"],
    answer: "安静",
    story_text: "禅宗的山水画里，有一种宁静致远的美感。",
    story_question: "禅宗画里有什么感觉？",
    story_options: ["宁静致远", "热闹吵闹", "忙乱"],
    story_answer: "宁静致远",
  },
  {
    level: "SRC800",
    character: "潇",
    word: "潇洒",
    sentence: "他很潇洒。",
    meaning_question: "\"潇\"的意思是什么？",
    options: ["自然", "强硬", "害怕"],
    answer: "自然",
    story_text: "他潇洒自如地吐露心声，感动了在场的每个人。",
    story_question: "他怎么吐露心声？",
    story_options: ["潇洒自如", "紧张", "害羞"],
    story_answer: "潇洒自如",
  },
  {
    level: "SRC800",
    character: "恋",
    word: "依恋",
    sentence: "依依不舍。",
    meaning_question: "\"恋\"的意思是什么？",
    options: ["喜欢", "讨厌", "忘记"],
    answer: "喜欢",
    story_text: "他对这片美丽的山水依依不舍，不愿离去。",
    story_question: "他为什么不愿离去？",
    story_options: ["依恋山水", "害怕", "生病"],
    story_answer: "依恋山水",
  },
  {
    level: "SRC800",
    character: "咳",
    word: "咳嗽",
    sentence: "他咳嗽不止。",
    meaning_question: "\"咳\"的意思是什么？",
    options: ["生病症状", "笑", "哭"],
    answer: "生病症状",
    story_text: "狂风暴雨后，树枝被吹得东倒西歪，叶子不停地飘落。",
    story_question: "狂风暴雨后树枝怎么样？",
    story_options: ["东倒西歪", "站得笔直", "完好无损"],
    story_answer: "东倒西歪",
  },
];

// 导出所有题库
export function getQuestionsByLevel(level: Level): Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] {
  switch (level) {
    case 'SRC300':
      return questionsSRC300;
    case 'SRC500':
      return [...questionsSRC300, ...questionsSRC500];
    case 'SRC800':
      return [...questionsSRC300, ...questionsSRC500, ...questionsSRC800];
    default:
      return questionsSRC300;
  }
}

export function getAllQuestions(): Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] {
  return [...questionsSRC300, ...questionsSRC500, ...questionsSRC800];
}

// 根据等级获取字表
export function getCharList(level: Level): string[] {
  switch (level) {
    case 'SRC300':
      return CHAR_LIST_300;
    case 'SRC500':
      return CHAR_LIST_500;
    case 'SRC800':
      return CHAR_LIST_800;
    default:
      return CHAR_LIST_300;
  }
}

// 根据等级获取词表
export function getWordList(level: Level): string[] {
  switch (level) {
    case 'SRC300':
      return WORD_LIST_300;
    case 'SRC500':
      return WORD_LIST_500;
    case 'SRC800':
      return WORD_LIST_800;
    default:
      return WORD_LIST_300;
  }
}
