import { Level, QuestionItem } from '@/lib/types';

// Seed question bank data for SRC-C system
// Each question has: character, word, sentence, meaning_question, options, answer
// And optional: story_text, story_question, story_options, story_answer (for part 4)

const questionsSRC300: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: 'SRC300',
    character: '大',
    word: '大小',
    sentence: '这个苹果很大。',
    meaning_question: '"大"的意思是什么？',
    options: ['很大', '很小', '很多'],
    answer: '很大',
    story_text: '大象用长鼻子喝水。小老鼠在旁边看着。',
    story_question: '谁用鼻子喝水？',
    story_options: ['大象', '小老鼠', '小鸟'],
    story_answer: '大象',
  },
  {
    level: 'SRC300',
    character: '小',
    word: '小鱼',
    sentence: '小鱼在水里游。',
    meaning_question: '"小"的意思是什么？',
    options: ['很小', '很大', '很多'],
    answer: '很小',
    story_text: '小猫在院子里追蝴蝶。蝴蝶飞走了。',
    story_question: '谁在追蝴蝶？',
    story_options: ['小猫', '蝴蝶', '小狗'],
    story_answer: '小猫',
  },
  {
    level: 'SRC300',
    character: '人',
    word: '人们',
    sentence: '公园里有很多人。',
    meaning_question: '"人"的意思是什么？',
    options: ['人类', '动物', '植物'],
    answer: '人类',
    story_text: '小明帮助老奶奶过马路。老奶奶说谢谢。',
    story_question: '谁帮助了老奶奶？',
    story_options: ['小明', '老奶奶', '路人'],
    story_answer: '小明',
  },
  {
    level: 'SRC300',
    character: '山',
    word: '山上',
    sentence: '山上有许多树。',
    meaning_question: '"山"是什么？',
    options: ['高高的地方', '平地', '水里'],
    answer: '高高的地方',
    story_text: '一家人去山上露营。他们在山上看到了星星。',
    story_question: '他们在山上看到了什么？',
    story_options: ['星星', '大海', '沙漠'],
    story_answer: '星星',
  },
  {
    level: 'SRC300',
    character: '水',
    word: '喝水',
    sentence: '我要喝水。',
    meaning_question: '"水"是什么？',
    options: ['液体', '固体', '气体'],
    answer: '液体',
    story_text: '小兔子口渴了，找到一条小河喝水。喝完水后，它又去采蘑菇了。',
    story_question: '小兔子喝完水后去做了什么？',
    story_options: ['采蘑菇', '睡觉', '跑步'],
    story_answer: '采蘑菇',
  },
  {
    level: 'SRC300',
    character: '火',
    word: '火车',
    sentence: '火车开过来了。',
    meaning_question: '"火"是什么？',
    options: ['燃烧的东西', '水', '风'],
    answer: '燃烧的东西',
    story_text: '冬天很冷，爸爸生了火。一家人围着火烤棉花糖。',
    story_question: '他们围着火做什么？',
    story_options: ['烤棉花糖', '唱歌', '跳舞'],
    story_answer: '烤棉花糖',
  },
  {
    level: 'SRC300',
    character: '天',
    word: '天空',
    sentence: '天空是蓝色的。',
    meaning_question: '"天"是什么？',
    options: ['头顶上的空间', '地面', '海洋'],
    answer: '头顶上的空间',
    story_text: '小鸟飞上了天。白云在它身边飘过。',
    story_question: '什么在天空飘过？',
    story_options: ['白云', '飞机', '气球'],
    story_answer: '白云',
  },
  {
    level: 'SRC300',
    character: '地',
    word: '地上',
    sentence: '地上有很多花。',
    meaning_question: '"地"是什么？',
    options: ['脚踩的地方', '天空', '水中'],
    answer: '脚踩的地方',
    story_text: '小鸡在地上找虫子吃。它找到一条大虫子。',
    story_question: '小鸡找到了什么？',
    story_options: ['一条虫子', '一条鱼', '一粒米'],
    story_answer: '一条虫子',
  },
  {
    level: 'SRC300',
    character: '花',
    word: '花朵',
    sentence: '花园里开满了花。',
    meaning_question: '"花"是什么？',
    options: ['植物开的部分', '动物', '石头'],
    answer: '植物开的部分',
    story_text: '春天来了，花园里开满了红花和黄花。蝴蝶在花上跳舞。',
    story_question: '蝴蝶在哪里跳舞？',
    story_options: ['花上', '树上', '水上'],
    story_answer: '花上',
  },
  {
    level: 'SRC300',
    character: '树',
    word: '大树',
    sentence: '大树下有一个人。',
    meaning_question: '"树"是什么？',
    options: ['长在土里的植物', '动物', '房子'],
    answer: '长在土里的植物',
    story_text: '小猴子爬上树摘桃子。它在树上开心地吃了起来。',
    story_question: '小猴子在树上做什么？',
    story_options: ['吃桃子', '睡觉', '唱歌'],
    story_answer: '吃桃子',
  },
  {
    level: 'SRC300',
    character: '鸟',
    word: '小鸟',
    sentence: '小鸟在天上飞。',
    meaning_question: '"鸟"是什么？',
    options: ['会飞的动物', '鱼', '虫子'],
    answer: '会飞的动物',
    story_text: '小鸟在树上做了窝。它在窝里下了蛋。',
    story_question: '小鸟在窝里做了什么？',
    story_options: ['下了蛋', '睡觉', '唱歌'],
    story_answer: '下了蛋',
  },
  {
    level: 'SRC300',
    character: '鱼',
    word: '小鱼',
    sentence: '河里有很多鱼。',
    meaning_question: '"鱼"是什么？',
    options: ['水里游的动物', '天上飞的', '地上跑的'],
    answer: '水里游的动物',
    story_text: '小猫在河边钓鱼。它等了很久，终于钓到了一条大鱼。',
    story_question: '小猫钓到了什么？',
    story_options: ['一条大鱼', '一只青蛙', '一个贝壳'],
    story_answer: '一条大鱼',
  },
  {
    level: 'SRC300',
    character: '马',
    word: '小马',
    sentence: '小马在草地上跑。',
    meaning_question: '"马"是什么？',
    options: ['一种动物', '一种水果', '一种花'],
    answer: '一种动物',
    story_text: '小马过河时不知道河水深不深。它问老牛，老牛说水很浅。',
    story_question: '老牛说河水怎么样？',
    story_options: ['很浅', '很深', '很冷'],
    story_answer: '很浅',
  },
  {
    level: 'SRC300',
    character: '牛',
    word: '牛奶',
    sentence: '我每天喝牛奶。',
    meaning_question: '"牛"是什么？',
    options: ['一种动物', '一种饮料', '一种水果'],
    answer: '一种动物',
    story_text: '农场里有一头老牛。它每天早上叫大家起床。',
    story_question: '老牛每天早上做什么？',
    story_options: ['叫大家起床', '耕地', '吃草'],
    story_answer: '叫大家起床',
  },
  {
    level: 'SRC300',
    character: '猴',
    word: '猴子',
    sentence: '小猴子爬上树。',
    meaning_question: '猴子是什么？',
    options: ['动物', '水果', '汽车'],
    answer: '动物',
    story_text: '孙悟空变成小鸟飞走了。',
    story_question: '孙悟空变成了什么？',
    story_options: ['小鸟', '大树', '石头'],
    story_answer: '小鸟',
  },
  {
    level: 'SRC300',
    character: '猫',
    word: '小猫',
    sentence: '小猫喜欢睡觉。',
    meaning_question: '"猫"是什么？',
    options: ['一种宠物', '一种食物', '一种颜色'],
    answer: '一种宠物',
    story_text: '小猫看见鱼缸里的鱼，想用爪子去抓。可是抓不到。',
    story_question: '小猫想抓什么？',
    story_options: ['鱼缸里的鱼', '蝴蝶', '老鼠'],
    story_answer: '鱼缸里的鱼',
  },
  {
    level: 'SRC300',
    character: '狗',
    word: '小狗',
    sentence: '小狗会看家。',
    meaning_question: '"狗"是什么？',
    options: ['一种动物', '一种植物', '一种天气'],
    answer: '一种动物',
    story_text: '小狗和小猫是好朋友。它们一起在草地上玩球。',
    story_question: '小狗和小猫一起做什么？',
    story_options: ['玩球', '游泳', '睡觉'],
    story_answer: '玩球',
  },
  {
    level: 'SRC300',
    character: '月',
    word: '月亮',
    sentence: '月亮在天上。',
    meaning_question: '"月"是什么？',
    options: ['天上的星体', '地上的花', '水里的鱼'],
    answer: '天上的星体',
    story_text: '中秋节晚上，一家人坐在院子里看月亮吃月饼。',
    story_question: '他们一边看月亮一边做什么？',
    story_options: ['吃月饼', '唱歌', '跳舞'],
    story_answer: '吃月饼',
  },
  {
    level: 'SRC300',
    character: '日',
    word: '日子',
    sentence: '今天是一个好日子。',
    meaning_question: '"日"的意思是什么？',
    options: ['太阳或一天', '月亮', '星星'],
    answer: '太阳或一天',
    story_text: '太阳从东边升起，照亮了大地。小朋友们都出来玩了。',
    story_question: '太阳从哪边升起？',
    story_options: ['东边', '西边', '南边'],
    story_answer: '东边',
  },
  {
    level: 'SRC300',
    character: '风',
    word: '大风',
    sentence: '今天风很大。',
    meaning_question: '"风"是什么？',
    options: ['空气的流动', '水的流动', '火的热度'],
    answer: '空气的流动',
    story_text: '大风把小树的叶子吹走了。小树摇摇晃晃的。',
    story_question: '大风吹走了什么？',
    story_options: ['小树的叶子', '小树', '花朵'],
    story_answer: '小树的叶子',
  },
];

const questionsSRC500: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: 'SRC500',
    character: '学',
    word: '学习',
    sentence: '我每天都在学习。',
    meaning_question: '"学"的意思是什么？',
    options: ['获取知识', '玩耍', '睡觉'],
    answer: '获取知识',
    story_text: '小明在学校学了很多新字。回家后他高兴地写给妈妈看。',
    story_question: '小明回家后做了什么？',
    story_options: ['写给妈妈看', '出去玩', '看电视'],
    story_answer: '写给妈妈看',
  },
  {
    level: 'SRC500',
    character: '读',
    word: '读书',
    sentence: '我每天读书。',
    meaning_question: '"读"的意思是什么？',
    options: ['看文字并念出来', '写字', '画画'],
    answer: '看文字并念出来',
    story_text: '小红喜欢读故事书。她读完一个故事后讲给弟弟听。',
    story_question: '小红读完故事后做了什么？',
    story_options: ['讲给弟弟听', '去睡觉', '做作业'],
    story_answer: '讲给弟弟听',
  },
  {
    level: 'SRC500',
    character: '写',
    word: '写字',
    sentence: '他在本子上写字。',
    meaning_question: '"写"的意思是什么？',
    options: ['用笔记录文字', '用嘴说话', '用脚走路'],
    answer: '用笔记录文字',
    story_text: '爷爷教小华写毛笔字。小华写的第一个字是"人"。',
    story_question: '小华写的第一个字是什么？',
    story_options: ['人', '大', '天'],
    story_answer: '人',
  },
  {
    level: 'SRC500',
    character: '听',
    word: '听音乐',
    sentence: '我喜欢听音乐。',
    meaning_question: '"听"的意思是什么？',
    options: ['用耳朵感受声音', '用眼睛看', '用手摸'],
    answer: '用耳朵感受声音',
    story_text: '音乐课上，老师弹了一首曲子。同学们安静地听着。',
    story_question: '谁弹了曲子？',
    story_options: ['老师', '同学', '校长'],
    story_answer: '老师',
  },
  {
    level: 'SRC500',
    character: '说',
    word: '说话',
    sentence: '请大声说话。',
    meaning_question: '"说"的意思是什么？',
    options: ['用嘴表达', '用耳听', '用眼看'],
    answer: '用嘴表达',
    story_text: '老师说上课要举手才能说话。小明举手回答了问题。',
    story_question: '小明回答问题前做了什么？',
    story_options: ['举手', '站起来', '走过去'],
    story_answer: '举手',
  },
  {
    level: 'SRC500',
    character: '想',
    word: '想法',
    sentence: '你在想什么？',
    meaning_question: '"想"的意思是什么？',
    options: ['在脑中思考', '用嘴说话', '用手做事'],
    answer: '在脑中思考',
    story_text: '小丽想了一想，然后画了一幅美丽的画。老师夸她画得好。',
    story_question: '小丽想完后做了什么？',
    story_options: ['画了一幅画', '写了一首诗', '唱了一首歌'],
    story_answer: '画了一幅画',
  },
  {
    level: 'SRC500',
    character: '知',
    word: '知道',
    sentence: '我知道答案了。',
    meaning_question: '"知"的意思是什么？',
    options: ['了解、明白', '不知道', '忘记了'],
    answer: '了解、明白',
    story_text: '小华终于知道了太阳为什么从东边升起。是老师告诉他的。',
    story_question: '谁告诉了小华答案？',
    story_options: ['老师', '妈妈', '同学'],
    story_answer: '老师',
  },
  {
    level: 'SRC500',
    character: '友',
    word: '朋友',
    sentence: '他是我的好朋友。',
    meaning_question: '"友"的意思是什么？',
    options: ['友好的关系', '敌人', '陌生人'],
    answer: '友好的关系',
    story_text: '两个好朋友一起去公园。他们一起荡秋千，玩得很开心。',
    story_question: '两个好朋友一起做了什么？',
    story_options: ['荡秋千', '读书', '画画'],
    story_answer: '荡秋千',
  },
  {
    level: 'SRC500',
    character: '家',
    word: '家人',
    sentence: '我爱我的家。',
    meaning_question: '"家"的意思是什么？',
    options: ['住的地方', '学校', '公园'],
    answer: '住的地方',
    story_text: '放学后，小明赶快回家。妈妈做了他最喜欢的饺子。',
    story_question: '妈妈做了什么？',
    story_options: ['饺子', '面条', '米饭'],
    story_answer: '饺子',
  },
  {
    level: 'SRC500',
    character: '国',
    word: '中国',
    sentence: '中国是一个大国。',
    meaning_question: '"国"的意思是什么？',
    options: ['国家', '城市', '村庄'],
    answer: '国家',
    story_text: '小明在地图上找到了中国。中国像一只大公鸡。',
    story_question: '中国在地图上像什么？',
    story_options: ['大公鸡', '大象', '蝴蝶'],
    story_answer: '大公鸡',
  },
  {
    level: 'SRC500',
    character: '春',
    word: '春天',
    sentence: '春天花开了。',
    meaning_question: '"春"是什么季节？',
    options: ['春季', '夏季', '冬季'],
    answer: '春季',
    story_text: '春天来了，小燕子从南方飞回来。它们在屋檐下筑了新巢。',
    story_question: '小燕子从哪里飞回来？',
    story_options: ['南方', '北方', '西方'],
    story_answer: '南方',
  },
  {
    level: 'SRC500',
    character: '夏',
    word: '夏天',
    sentence: '夏天很热。',
    meaning_question: '"夏"是什么季节？',
    options: ['夏季', '冬季', '春季'],
    answer: '夏季',
    story_text: '夏天到了，小朋友们去海边游泳。他们在沙滩上堆了一个大城堡。',
    story_question: '小朋友们在沙滩上做了什么？',
    story_options: ['堆城堡', '放风筝', '跑步'],
    story_answer: '堆城堡',
  },
  {
    level: 'SRC500',
    character: '秋',
    word: '秋天',
    sentence: '秋天叶子黄了。',
    meaning_question: '"秋"是什么季节？',
    options: ['秋季', '春季', '夏季'],
    answer: '秋季',
    story_text: '秋天的果园里，苹果红了，梨子黄了。农民伯伯在采摘水果。',
    story_question: '谁在采摘水果？',
    story_options: ['农民伯伯', '小朋友', '小鸟'],
    story_answer: '农民伯伯',
  },
  {
    level: 'SRC500',
    character: '冬',
    word: '冬天',
    sentence: '冬天下雪了。',
    meaning_question: '"冬"是什么季节？',
    options: ['冬季', '夏季', '春季'],
    answer: '冬季',
    story_text: '冬天下了大雪，小朋友们在院子里堆了一个大雪人。他们给雪人戴了红帽子。',
    story_question: '雪人戴了什么？',
    story_options: ['红帽子', '围巾', '手套'],
    story_answer: '红帽子',
  },
  {
    level: 'SRC500',
    character: '星',
    word: '星星',
    sentence: '天上有很多星星。',
    meaning_question: '"星"是什么？',
    options: ['夜空中发光的天体', '地上的石头', '水中的鱼'],
    answer: '夜空中发光的天体',
    story_text: '晚上，小明看到一颗流星飞过。他赶紧许了一个愿望。',
    story_question: '小明看到流星后做了什么？',
    story_options: ['许了愿望', '去睡觉', '叫妈妈'],
    story_answer: '许了愿望',
  },
  {
    level: 'SRC500',
    character: '河',
    word: '小河',
    sentence: '小河里有鱼。',
    meaning_question: '"河"是什么？',
    options: ['流动的水道', '山', '路'],
    answer: '流动的水道',
    story_text: '小河的水清清的，可以看到河底的石头。小鱼在石头之间游来游去。',
    story_question: '可以看到河底的什么？',
    story_options: ['石头', '金子', '贝壳'],
    story_answer: '石头',
  },
  {
    level: 'SRC500',
    character: '海',
    word: '大海',
    sentence: '大海很蓝。',
    meaning_question: '"海"是什么？',
    options: ['大面积的咸水', '小河', '湖泊'],
    answer: '大面积的咸水',
    story_text: '小明第一次看到大海，非常激动。浪花拍打着沙滩，发出哗哗的声音。',
    story_question: '浪花发出了什么声音？',
    story_options: ['哗哗声', '嗡嗡声', '叮叮声'],
    story_answer: '哗哗声',
  },
  {
    level: 'SRC500',
    character: '路',
    word: '走路',
    sentence: '这条路很长。',
    meaning_question: '"路"是什么？',
    options: ['行走的地方', '天空', '水面'],
    answer: '行走的地方',
    story_text: '小兔子的家和学校之间有一条小路。每天它沿着这条路去上学。',
    story_question: '小兔子每天走小路去哪里？',
    story_options: ['学校', '公园', '超市'],
    story_answer: '学校',
  },
  {
    level: 'SRC500',
    character: '桥',
    word: '小桥',
    sentence: '河上有一座桥。',
    meaning_question: '"桥"是什么？',
    options: ['跨越水面的建筑', '房子', '船'],
    answer: '跨越水面的建筑',
    story_text: '小羊走过小桥，到对面的草地去吃草。桥下的水哗哗地流。',
    story_question: '小羊过桥去做什么？',
    story_options: ['吃草', '喝水', '睡觉'],
    story_answer: '吃草',
  },
  {
    level: 'SRC500',
    character: '云',
    word: '白云',
    sentence: '天上飘着白云。',
    meaning_question: '"云"是什么？',
    options: ['天空中的水汽团', '地上的花', '水中的鱼'],
    answer: '天空中的水汽团',
    story_text: '小白看着天上的白云，说那朵云像一只兔子。妹妹说像一只猫。',
    story_question: '小白觉得那朵云像什么？',
    story_options: ['兔子', '猫', '狗'],
    story_answer: '兔子',
  },
];

const questionsSRC800: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: 'SRC800',
    character: '梦',
    word: '梦想',
    sentence: '他有一个美丽的梦想。',
    meaning_question: '"梦"的意思是什么？',
    options: ['睡觉时的想象', '吃的东西', '穿的衣服'],
    answer: '睡觉时的想象',
    story_text: '小丽梦想成为一名画家。她每天画画，终于在画展上展出了自己的作品。',
    story_question: '小丽在画展上做了什么？',
    story_options: ['展出了自己的作品', '买了画', '看了画'],
    story_answer: '展出了自己的作品',
  },
  {
    level: 'SRC800',
    character: '勇',
    word: '勇敢',
    sentence: '他是一个勇敢的人。',
    meaning_question: '"勇"的意思是什么？',
    options: ['不怕困难', '害怕', '懒惰'],
    answer: '不怕困难',
    story_text: '小华勇敢地站在台上演讲。虽然很紧张，但他还是说完了每一个字。',
    story_question: '小华在台上做了什么？',
    story_options: ['演讲', '唱歌', '跳舞'],
    story_answer: '演讲',
  },
  {
    level: 'SRC800',
    character: '聪',
    word: '聪明',
    sentence: '她是一个聪明的孩子。',
    meaning_question: '"聪"的意思是什么？',
    options: ['脑子灵活', '身体强壮', '跑得快'],
    answer: '脑子灵活',
    story_text: '聪明的小明用一根绳子就把门修好了。大家都夸他想办法快。',
    story_question: '小明用什么修好了门？',
    story_options: ['一根绳子', '一把锤子', '一扇新门'],
    story_answer: '一根绳子',
  },
  {
    level: 'SRC800',
    character: '善',
    word: '善良',
    sentence: '她是一个善良的人。',
    meaning_question: '"善"的意思是什么？',
    options: ['心地好', '很凶', '很懒'],
    answer: '心地好',
    story_text: '善良的老奶奶收留了一只流浪猫。她每天给猫喂食，猫慢慢变得胖了。',
    story_question: '猫后来变得怎样了？',
    story_options: ['变胖了', '跑走了', '变瘦了'],
    story_answer: '变胖了',
  },
  {
    level: 'SRC800',
    character: '文',
    word: '文化',
    sentence: '中国文化很丰富。',
    meaning_question: '"文"的意思是什么？',
    options: ['文字与文化', '数字', '颜色'],
    answer: '文字与文化',
    story_text: '学校举办了文化节。同学们表演了京剧、书法和太极拳。',
    story_question: '同学们没有表演什么？',
    story_options: ['游泳', '京剧', '书法'],
    story_answer: '游泳',
  },
  {
    level: 'SRC800',
    character: '理',
    word: '道理',
    sentence: '这个道理我明白了。',
    meaning_question: '"理"的意思是什么？',
    options: ['道理、逻辑', '力气', '速度'],
    answer: '道理、逻辑',
    story_text: '老师讲了一个道理：种瓜得瓜，种豆得豆。意思是你种什么就收什么。',
    story_question: '"种瓜得瓜"的意思是什么？',
    story_options: ['种什么就收什么', '种瓜可以得豆', '种豆可以得瓜'],
    story_answer: '种什么就收什么',
  },
  {
    level: 'SRC800',
    character: '志',
    word: '志向',
    sentence: '他有远大的志向。',
    meaning_question: '"志"的意思是什么？',
    options: ['目标和愿望', '害怕', '懒惰'],
    answer: '目标和愿望',
    story_text: '小刚立志要当一名科学家。他每天做实验，终于在比赛中获得了奖。',
    story_question: '小刚在比赛中获得了什么？',
    story_options: ['奖', '朋友', '钱'],
    story_answer: '奖',
  },
  {
    level: 'SRC800',
    character: '节',
    word: '节日',
    sentence: '春节是最重要的节日。',
    meaning_question: '"节"在这里的意思是什么？',
    options: ['庆祝的日子', '节省', '一节课'],
    answer: '庆祝的日子',
    story_text: '春节时，全家人围在一起吃年夜饭。然后一起看春节晚会。',
    story_question: '春节时全家人一起做什么？',
    story_options: ['吃年夜饭', '去旅行', '去上学'],
    story_answer: '吃年夜饭',
  },
  {
    level: 'SRC800',
    character: '庆',
    word: '庆祝',
    sentence: '我们庆祝生日。',
    meaning_question: '"庆"的意思是什么？',
    options: ['高兴地纪念', '难过', '忘记'],
    answer: '高兴地纪念',
    story_text: '同学们庆祝小红获得了一等奖。大家一起唱了歌，还吃了蛋糕。',
    story_question: '同学们庆祝时吃了什么？',
    story_options: ['蛋糕', '饺子', '面条'],
    story_answer: '蛋糕',
  },
  {
    level: 'SRC800',
    character: '传',
    word: '传说',
    sentence: '这是一个古老的传说。',
    meaning_question: '"传"在这里的意思是什么？',
    options: ['流传', '传递', '转变'],
    answer: '流传',
    story_text: '传说嫦娥飞到了月亮上。人们在中秋节会想起这个故事。',
    story_question: '嫦娥飞到了哪里？',
    story_options: ['月亮上', '太阳上', '星星上'],
    story_answer: '月亮上',
  },
  {
    level: 'SRC800',
    character: '族',
    word: '民族',
    sentence: '中国有五十六个民族。',
    meaning_question: '"族"的意思是什么？',
    options: ['有共同特征的人群', '一个人', '一种动物'],
    answer: '有共同特征的人群',
    story_text: '不同民族有不同的服装和习惯。傣族人喜欢泼水节，蒙古族人喜欢骑马。',
    story_question: '傣族人喜欢什么节日？',
    story_options: ['泼水节', '春节', '中秋节'],
    story_answer: '泼水节',
  },
  {
    level: 'SRC800',
    character: '筑',
    word: '建筑',
    sentence: '这座建筑很漂亮。',
    meaning_question: '"筑"的意思是什么？',
    options: ['建造', '拆掉', '画画'],
    answer: '建造',
    story_text: '古代工人筑起了长城。长城是世界最长的墙，可以在太空看到。',
    story_question: '什么可以在太空看到？',
    story_options: ['长城', '故宫', '天安门'],
    story_answer: '长城',
  },
  {
    level: 'SRC800',
    character: '创',
    word: '创造',
    sentence: '他创造了新纪录。',
    meaning_question: '"创"的意思是什么？',
    options: ['开始做新的', '毁灭', '复制'],
    answer: '开始做新的',
    story_text: '蔡伦创造了造纸术。有了纸，人们就不用在竹子上写字了。',
    story_question: '蔡伦创造了什么？',
    story_options: ['造纸术', '火药', '指南针'],
    story_answer: '造纸术',
  },
  {
    level: 'SRC800',
    character: '历',
    word: '历史',
    sentence: '中国有悠久的历史。',
    meaning_question: '"历"在这里的意思是什么？',
    options: ['过去的经历', '日历', '力气'],
    answer: '过去的经历',
    story_text: '博物馆里有很多历史文物。小明看到了几千年前的青铜器。',
    story_question: '小明在博物馆看到了什么？',
    story_options: ['青铜器', '电脑', '手机'],
    story_answer: '青铜器',
  },
  {
    level: 'SRC800',
    character: '诗',
    word: '古诗',
    sentence: '我会背很多古诗。',
    meaning_question: '"诗"是什么？',
    options: ['有韵律的文学', '故事', '信件'],
    answer: '有韵律的文学',
    story_text: '李白写了很多著名的诗。其中一首写道：床前明月光，疑是地上霜。',
    story_question: '诗中写到了什么？',
    story_options: ['明月光', '太阳', '大海'],
    story_answer: '明月光',
  },
  {
    level: 'SRC800',
    character: '武',
    word: '武术',
    sentence: '中国武术很有名。',
    meaning_question: '"武"的意思是什么？',
    options: ['与格斗有关', '与音乐有关', '与画画有关'],
    answer: '与格斗有关',
    story_text: '少林寺的和尚练习武术。他们的功夫非常高强。',
    story_question: '少林寺的和尚练习什么？',
    story_options: ['武术', '音乐', '画画'],
    story_answer: '武术',
  },
  {
    level: 'SRC800',
    character: '德',
    word: '品德',
    sentence: '要有好的品德。',
    meaning_question: '"德"的意思是什么？',
    options: ['好的品行', '力气', '速度'],
    answer: '好的品行',
    story_text: '孔子说，有德的人朋友多。意思是品德好的人，大家都愿意和他做朋友。',
    story_question: '孔子说有德的人会怎样？',
    story_options: ['朋友多', '力气大', '跑得快'],
    story_answer: '朋友多',
  },
  {
    level: 'SRC800',
    character: '信',
    word: '信任',
    sentence: '朋友之间要互相信任。',
    meaning_question: '"信"在这里的意思是什么？',
    options: ['相信', '信件', '信息'],
    answer: '相信',
    story_text: '小华答应帮小明复习功课。他信守承诺，按时来了。',
    story_question: '小华做了什么？',
    story_options: ['信守承诺按时来了', '忘记了', '去玩了'],
    story_answer: '信守承诺按时来了',
  },
  {
    level: 'SRC800',
    character: '敬',
    word: '尊敬',
    sentence: '我们要尊敬老师。',
    meaning_question: '"敬"的意思是什么？',
    options: ['尊重', '害怕', '忽略'],
    answer: '尊重',
    story_text: '孔子说，尊敬别人的人也会被别人尊敬。这就是"己所不欲，勿施于人"。',
    story_question: '"己所不欲，勿施于人"是什么意思？',
    story_options: ['自己不想要的不要给别人', '自己想要什么就给什么', '不想做就不做'],
    story_answer: '自己不想要的不要给别人',
  },
  {
    level: 'SRC800',
    character: '慧',
    word: '智慧',
    sentence: '老人有很多智慧。',
    meaning_question: '"慧"的意思是什么？',
    options: ['聪明的才能', '力气', '速度'],
    answer: '聪明的才能',
    story_text: '诸葛亮用智慧借了十万支箭。他让人在船上扎草人，利用大雾天气骗了曹操。',
    story_question: '诸葛亮用什么方法借箭？',
    story_options: ['船上扎草人', '直接去拿', '买来的'],
    story_answer: '船上扎草人',
  },
];

export const ALL_QUESTIONS: Record<Level, Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[]> = {
  SRC300: questionsSRC300,
  SRC500: questionsSRC500,
  SRC800: questionsSRC800,
};
