import { Level, QuestionItem } from '@/lib/types';

// SRC300 题库 - 基于阅读高频字300字库
// 每道题包含：字形识别(character)、词汇识别(word+meaning)、句子识别(sentence)、理解测试(story)

const questionsSRC300: Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    level: 'SRC300',
    character: '人',
    word: '人们',
    sentence: '公园里有很多人。',
    meaning_question: '"人"的意思是什么？',
    options: ['人物', '动物', '植物'],
    answer: '人物',
    story_text: '人们来到小村子，想找一位神仙。',
    story_question: '人们想找谁？',
    story_options: ['神仙', '国王', '妖怪'],
    story_answer: '神仙',
  },
  {
    level: 'SRC300',
    character: '我',
    word: '我们',
    sentence: '我们是好朋友。',
    meaning_question: '"我"是什么？',
    options: ['自己', '别人', '动物'],
    answer: '自己',
    story_text: '我对好朋友说："我们一起去玩吧！"',
    story_question: '谁想去玩？',
    story_options: ['我', '老师', '爸爸'],
    story_answer: '我',
  },
  {
    level: 'SRC300',
    character: '你',
    word: '你的',
    sentence: '你的书包在哪里？',
    meaning_question: '"你"是指谁？',
    options: ['对方', '自己', '别人'],
    answer: '对方',
    story_text: '你看见那只小猫了吗？它在树下。',
    story_question: '小猫在哪里？',
    story_options: ['树下', '房子里', '水里'],
    story_answer: '树下',
  },
  {
    level: 'SRC300',
    character: '他',
    word: '他们',
    sentence: '他们在学校上课。',
    meaning_question: '"他"是指谁？',
    options: ['另一个男的', '自己', '动物'],
    answer: '另一个男的',
    story_text: '他是勇敢的英雄，帮大家打败了妖怪。',
    story_question: '他是什么样的人？',
    story_options: ['勇敢的英雄', '胆小的人', '坏人'],
    story_answer: '勇敢的英雄',
  },
  {
    level: 'SRC300',
    character: '她',
    word: '她的',
    sentence: '她的名字叫小红。',
    meaning_question: '"她"是指谁？',
    options: ['女的', '男的', '动物'],
    answer: '女的',
    story_text: '她是公主，住在漂亮的城堡里。',
    story_question: '她住在哪里？',
    story_options: ['城堡', '山洞', '森林'],
    story_answer: '城堡',
  },
  {
    level: 'SRC300',
    character: '大',
    word: '大小',
    sentence: '这个苹果很大。',
    meaning_question: '"大"的意思是什么？',
    options: ['很大', '很小', '很多'],
    answer: '很大',
    story_text: '大象用长鼻子喝水。小老鼠在旁边看着。',
    story_question: '谁用鼻子喝水？',
    story_options: ['大象', '小老鼠', '小鸟'],
    story_answer: '大象',
  },
  {
    level: 'SRC300',
    character: '小',
    word: '小鱼',
    sentence: '小鱼在水里游。',
    meaning_question: '"小"的意思是什么？',
    options: ['很小', '很大', '很多'],
    answer: '很小',
    story_text: '小猫在院子里追蝴蝶。蝴蝶飞走了。',
    story_question: '谁在追蝴蝶？',
    story_options: ['小猫', '小狗', '小鸟'],
    story_answer: '小猫',
  },
  {
    level: 'SRC300',
    character: '多',
    word: '很多',
    sentence: '树上有很多苹果。',
    meaning_question: '"多"的意思是什么？',
    options: ['数量大', '很少', '不大'],
    answer: '数量大',
    story_text: '花园里开了很多花，红的黄的都有。',
    story_question: '花园里有什么？',
    story_options: ['很多花', '很多树', '很多石头'],
    story_answer: '很多花',
  },
  {
    level: 'SRC300',
    character: '少',
    word: '少数',
    sentence: '少数人还没有到。',
    meaning_question: '"少"的意思是什么？',
    options: ['数量小', '很大', '很多'],
    answer: '数量小',
    story_text: '草地上只有少数几朵花，其他都是草。',
    story_question: '草地上花多还是少？',
    story_options: ['少', '很多', '数不清'],
    story_answer: '少',
  },
  {
    level: 'SRC300',
    character: '高',
    word: '高山',
    sentence: '那座山很高。',
    meaning_question: '"高"的意思是什么？',
    options: ['从下到上很远', '很矮', '很宽'],
    answer: '从下到上很远',
    story_text: '小明爬上了高山，看见了大海。',
    story_question: '小明看见了什么？',
    story_options: ['大海', '学校', '商店'],
    story_answer: '大海',
  },
  {
    level: 'SRC300',
    character: '低',
    word: '高低',
    sentence: '请把声音放低。',
    meaning_question: '"低"的意思是什么？',
    options: ['不高的', '很大的', '很快的'],
    answer: '不高的',
    story_text: '小鸟飞得很低，快要到地上了。',
    story_question: '小鸟飞得怎么样？',
    story_options: ['很低', '很高', '很快'],
    story_answer: '很低',
  },
  {
    level: 'SRC300',
    character: '长',
    word: '长长',
    sentence: '这条路很长。',
    meaning_question: '"长"的意思是什么？',
    options: ['从一头到另一头很远', '很短', '很宽'],
    answer: '从一头到另一头很远',
    story_text: '蛇有长长的身体，可以在地上爬。',
    story_question: '蛇的身体怎么样？',
    story_options: ['长长的', '短短的', '圆圆的'],
    story_answer: '长长的',
  },
  {
    level: 'SRC300',
    character: '短',
    word: '短小',
    sentence: '这支铅笔很短了。',
    meaning_question: '"短"的意思是什么？',
    options: ['不长的', '很长的', '很粗的'],
    answer: '不长的',
    story_text: '兔子的尾巴很短，猫的尾巴很长。',
    story_question: '谁的尾巴短？',
    story_options: ['兔子', '猫', '狗'],
    story_answer: '兔子',
  },
  {
    level: 'SRC300',
    character: '好',
    word: '好看',
    sentence: '这朵花真好看。',
    meaning_question: '"好"的意思是什么？',
    options: ['不错的', '坏的', '丑的'],
    answer: '不错的',
    story_text: '老师说小红是个好孩子，因为她帮助同学。',
    story_question: '小红为什么是好孩子？',
    story_options: ['帮助同学', '会画画', '跑得快'],
    story_answer: '帮助同学',
  },
  {
    level: 'SRC300',
    character: '新',
    word: '新年',
    sentence: '新年快乐！',
    meaning_question: '"新"的意思是什么？',
    options: ['刚有的', '旧的', '不好的'],
    answer: '刚有的',
    story_text: '新年到了，孩子们穿上新衣服，开心地跑出去玩。',
    story_question: '孩子们穿上什么？',
    story_options: ['新衣服', '旧衣服', '校服'],
    story_answer: '新衣服',
  },
  {
    level: 'SRC300',
    character: '上',
    word: '上面',
    sentence: '书在桌子上。',
    meaning_question: '"上"表示什么？',
    options: ['高的位置', '低的位置', '旁边'],
    answer: '高的位置',
    story_text: '小猫跳上了桌子，把花瓶打翻了。',
    story_question: '花瓶怎么了？',
    story_options: ['被小猫打翻了', '很漂亮', '很大'],
    story_answer: '被小猫打翻了',
  },
  {
    level: 'SRC300',
    character: '下',
    word: '下面',
    sentence: '猫在桌子下面。',
    meaning_question: '"下"表示什么？',
    options: ['低的位置', '高的位置', '旁边'],
    answer: '低的位置',
    story_text: '下雨了，孩子们跑回家躲雨。',
    story_question: '孩子们为什么跑回家？',
    story_options: ['下雨了', '天黑了', '吃饭了'],
    story_answer: '下雨了',
  },
  {
    level: 'SRC300',
    character: '里',
    word: '里面',
    sentence: '房间里面很暖和。',
    meaning_question: '"里"表示什么？',
    options: ['内部', '外部', '旁边'],
    answer: '内部',
    story_text: '山洞里面很黑，但是有宝藏。',
    story_question: '山洞里有什么？',
    story_options: ['宝藏', '太阳', '花'],
    story_answer: '宝藏',
  },
  {
    level: 'SRC300',
    character: '外',
    word: '外面',
    sentence: '外面在下雨。',
    meaning_question: '"外"表示什么？',
    options: ['外部', '内部', '上面'],
    answer: '外部',
    story_text: '外面刮大风了，大树被吹得摇摇晃晃。',
    story_question: '外面怎么了？',
    story_options: ['刮大风', '出太阳', '很安静'],
    story_answer: '刮大风',
  },
  {
    level: 'SRC300',
    character: '天',
    word: '天空',
    sentence: '天空中有白云。',
    meaning_question: '"天"的意思是什么？',
    options: ['头顶上的空间', '地面', '水里'],
    answer: '头顶上的空间',
    story_text: '天上的星星一闪一闪的，月亮又大又圆。',
    story_question: '天上有什么？',
    story_options: ['星星和月亮', '太阳和云', '鸟和飞机'],
    story_answer: '星星和月亮',
  },
  {
    level: 'SRC300',
    character: '山',
    word: '高山',
    sentence: '远处有一座山。',
    meaning_question: '"山"是什么？',
    options: ['很高的大地', '水面', '房子'],
    answer: '很高的大地',
    story_text: '山上长满了树，山下有一条小河。',
    story_question: '山下有什么？',
    story_options: ['小河', '城堡', '学校'],
    story_answer: '小河',
  },
  {
    level: 'SRC300',
    character: '水',
    word: '河水',
    sentence: '河水很清。',
    meaning_question: '"水"是什么？',
    options: ['液体', '固体', '气体'],
    answer: '液体',
    story_text: '小鱼在水里游来游去，开心极了。',
    story_question: '小鱼在哪里游？',
    story_options: ['水里', '天上', '地上'],
    story_answer: '水里',
  },
  {
    level: 'SRC300',
    character: '火',
    word: '火山',
    sentence: '火山会喷火。',
    meaning_question: '"火"是什么？',
    options: ['燃烧的东西', '水', '风'],
    answer: '燃烧的东西',
    story_text: '妈妈用火做饭，好吃极了。但是火很危险，不能碰！',
    story_question: '火能做什么？',
    story_options: ['做饭', '喝水', '飞行'],
    story_answer: '做饭',
  },
  {
    level: 'SRC300',
    character: '风',
    word: '大风',
    sentence: '今天风很大。',
    meaning_question: '"风"是什么？',
    options: ['空气流动', '雨', '云'],
    answer: '空气流动',
    story_text: '大风把小树的叶子都吹走了。',
    story_question: '风把什么吹走了？',
    story_options: ['叶子', '花', '果子'],
    story_answer: '叶子',
  },
  {
    level: 'SRC300',
    character: '云',
    word: '云彩',
    sentence: '天上有白云。',
    meaning_question: '"云"是什么？',
    options: ['天上的白色东西', '地上的草', '水里的鱼'],
    answer: '天上的白色东西',
    story_text: '云彩变成了各种形状，有的像小狗，有的像大山。',
    story_question: '云彩像什么？',
    story_options: ['小狗和大山', '人和树', '鱼和鸟'],
    story_answer: '小狗和大山',
  },
  {
    level: 'SRC300',
    character: '雨',
    word: '下雨',
    sentence: '外面下雨了。',
    meaning_question: '"雨"是什么？',
    options: ['从天上落下的水', '风', '太阳'],
    answer: '从天上落下的水',
    story_text: '下雨了，小青蛙高兴地跳进池塘里。',
    story_question: '谁高兴地跳进池塘？',
    story_options: ['小青蛙', '小猫', '小鸟'],
    story_answer: '小青蛙',
  },
  {
    level: 'SRC300',
    character: '一',
    word: '一个',
    sentence: '桌上有一个苹果。',
    meaning_question: '"一"是什么意思？',
    options: ['数量1', '数量2', '很多'],
    answer: '数量1',
    story_text: '一只小鸟停在树枝上，唱起了歌。',
    story_question: '有几只小鸟？',
    story_options: ['一只', '两只', '三只'],
    story_answer: '一只',
  },
  {
    level: 'SRC300',
    character: '百',
    word: '一百',
    sentence: '这里有一百个孩子。',
    meaning_question: '"百"是什么意思？',
    options: ['数量100', '数量10', '数量1000'],
    answer: '数量100',
    story_text: '村子里有一百个人，大家都是好朋友。',
    story_question: '村子里有多少人？',
    story_options: ['一百个', '十个', '一个'],
    story_answer: '一百个',
  },
  {
    level: 'SRC300',
    character: '来',
    word: '回来',
    sentence: '他回来了。',
    meaning_question: '"来"的意思是什么？',
    options: ['到这里', '离开这里', '待在原地'],
    answer: '到这里',
    story_text: '春天来了，花园里的花都开了。',
    story_question: '花园里的花怎么了？',
    story_options: ['开了', '关了', '飞了'],
    story_answer: '开了',
  },
  {
    level: 'SRC300',
    character: '去',
    word: '出去',
    sentence: '我们去学校。',
    meaning_question: '"去"的意思是什么？',
    options: ['离开这里到这里', '到这里来', '待在原地'],
    answer: '离开这里到这里',
    story_text: '小明去图书馆看书，学到了很多知识。',
    story_question: '小明去了哪里？',
    story_options: ['图书馆', '学校', '商店'],
    story_answer: '图书馆',
  },
  {
    level: 'SRC300',
    character: '看',
    word: '看见',
    sentence: '我看见一只蝴蝶。',
    meaning_question: '"看"的意思是什么？',
    options: ['用眼睛观察', '用耳朵听', '用手摸'],
    answer: '用眼睛观察',
    story_text: '小猴子看见水里的月亮，想把它捞上来。',
    story_question: '小猴子想捞什么？',
    story_options: ['月亮', '太阳', '鱼'],
    story_answer: '月亮',
  },
  {
    level: 'SRC300',
    character: '听',
    word: '听见',
    sentence: '我听见鸟在叫。',
    meaning_question: '"听"的意思是什么？',
    options: ['用耳朵感受声音', '用眼睛看', '用手摸'],
    answer: '用耳朵感受声音',
    story_text: '小白兔听见狼来了，赶紧跑回家躲起来。',
    story_question: '小白兔为什么跑回家？',
    story_options: ['听见狼来了', '听见妈妈叫', '想睡觉'],
    story_answer: '听见狼来了',
  },
  {
    level: 'SRC300',
    character: '说',
    word: '说话',
    sentence: '请大声说话。',
    meaning_question: '"说"的意思是什么？',
    options: ['用嘴表达', '用眼看', '用耳听'],
    answer: '用嘴表达',
    story_text: '老师说话的时候，大家都在认真听。',
    story_question: '大家怎么听老师说话？',
    story_options: ['认真听', '玩闹', '睡觉'],
    story_answer: '认真听',
  },
  {
    level: 'SRC300',
    character: '笑',
    word: '大笑',
    sentence: '妹妹笑得很开心。',
    meaning_question: '"笑"的意思是什么？',
    options: ['高兴的表情', '难过', '生气'],
    answer: '高兴的表情',
    story_text: '小丑表演节目，孩子们大笑起来。',
    story_question: '孩子们为什么大笑？',
    story_options: ['小丑表演节目', '下雨了', '肚子疼'],
    story_answer: '小丑表演节目',
  },
  {
    level: 'SRC300',
    character: '哭',
    word: '哭了',
    sentence: '小宝宝哭了。',
    meaning_question: '"哭"的意思是什么？',
    options: ['难过流眼泪', '高兴', '睡觉'],
    answer: '难过流眼泪',
    story_text: '小女孩找不到妈妈，着急地哭了。',
    story_question: '小女孩为什么哭？',
    story_options: ['找不到妈妈', '想吃东西', '想玩'],
    story_answer: '找不到妈妈',
  },
  {
    level: 'SRC300',
    character: '吃',
    word: '吃饭',
    sentence: '我们吃饭吧。',
    meaning_question: '"吃"的意思是什么？',
    options: ['把食物放进嘴里', '喝水', '睡觉'],
    answer: '把食物放进嘴里',
    story_text: '小兔子在草地上吃草，吃得可开心了。',
    story_question: '小兔子在吃什么？',
    story_options: ['草', '肉', '鱼'],
    story_answer: '草',
  },
  {
    level: 'SRC300',
    character: '跑',
    word: '跑步',
    sentence: '他跑得很快。',
    meaning_question: '"跑"的意思是什么？',
    options: ['快速走', '慢慢走', '站着'],
    answer: '快速走',
    story_text: '小马在草地上跑步，越跑越快。',
    story_question: '小马在做什么？',
    story_options: ['跑步', '睡觉', '喝水'],
    story_answer: '跑步',
  },
  {
    level: 'SRC300',
    character: '跳',
    word: '跳起来',
    sentence: '青蛙跳进水里。',
    meaning_question: '"跳"的意思是什么？',
    options: ['双脚离地弹起', '走', '爬'],
    answer: '双脚离地弹起',
    story_text: '小猴子从这棵树跳到那棵树，开心极了。',
    story_question: '小猴子怎么从一棵树到另一棵树？',
    story_options: ['跳', '走', '飞'],
    story_answer: '跳',
  },
  {
    level: 'SRC300',
    character: '飞',
    word: '飞走',
    sentence: '小鸟飞走了。',
    meaning_question: '"飞"的意思是什么？',
    options: ['在空中移动', '在地上走', '在水里游'],
    answer: '在空中移动',
    story_text: '小鸟张开翅膀飞走了，飞过高山，飞过大海。',
    story_question: '小鸟飞过了什么？',
    story_options: ['高山和大海', '学校', '花园'],
    story_answer: '高山和大海',
  },
  {
    level: 'SRC300',
    character: '找',
    word: '找到',
    sentence: '我找到了钥匙。',
    meaning_question: '"找"的意思是什么？',
    options: ['寻找', '扔掉', '看'],
    answer: '寻找',
    story_text: '小猫找不到妈妈，到处找啊找。终于找到了！',
    story_question: '小猫最后找到了什么？',
    story_options: ['妈妈', '鱼', '玩具'],
    story_answer: '妈妈',
  },
  {
    level: 'SRC300',
    character: '帮',
    word: '帮助',
    sentence: '请帮助我。',
    meaning_question: '"帮"的意思是什么？',
    options: ['协助', '阻碍', '离开'],
    answer: '协助',
    story_text: '大哥哥帮助小妹妹过马路，真勇敢！',
    story_question: '大哥哥帮助谁过马路？',
    story_options: ['小妹妹', '老奶奶', '小狗'],
    story_answer: '小妹妹',
  },
  {
    level: 'SRC300',
    character: '猴',
    word: '猴子',
    sentence: '猴子喜欢吃香蕉。',
    meaning_question: '猴子是什么？',
    options: ['动物', '水果', '汽车'],
    answer: '动物',
    story_text: '小猴子爬上树，摘了一个大桃子。',
    story_question: '小猴子摘了什么？',
    story_options: ['桃子', '香蕉', '苹果'],
    story_answer: '桃子',
  },
  {
    level: 'SRC300',
    character: '鸟',
    word: '小鸟',
    sentence: '小鸟在唱歌。',
    meaning_question: '鸟是什么？',
    options: ['会飞的动物', '鱼', '虫子'],
    answer: '会飞的动物',
    story_text: '小鸟在树上唱歌，歌声真好听。',
    story_question: '小鸟的歌声怎么样？',
    story_options: ['好听', '难听', '很吵'],
    story_answer: '好听',
  },
  {
    level: 'SRC300',
    character: '马',
    word: '小马',
    sentence: '小马在吃草。',
    meaning_question: '马是什么？',
    options: ['动物', '植物', '食物'],
    answer: '动物',
    story_text: '小马过河的时候，不知道水有多深。',
    story_question: '小马在做什么？',
    story_options: ['过河', '爬山', '睡觉'],
    story_answer: '过河',
  },
  {
    level: 'SRC300',
    character: '狗',
    word: '小狗',
    sentence: '小狗在门口。',
    meaning_question: '狗是什么？',
    options: ['动物', '植物', '石头'],
    answer: '动物',
    story_text: '小狗看见主人回来，高兴地摇尾巴。',
    story_question: '小狗为什么摇尾巴？',
    story_options: ['看见主人回来', '想吃东西', '害怕'],
    story_answer: '看见主人回来',
  },
  {
    level: 'SRC300',
    character: '龙',
    word: '龙王',
    sentence: '龙是一种神兽。',
    meaning_question: '龙是什么？',
    options: ['传说中的神兽', '普通的鱼', '一种树'],
    answer: '传说中的神兽',
    story_text: '龙王住在海底的宫殿里，掌管着大海。',
    story_question: '龙王住在哪里？',
    story_options: ['海底', '山上', '天上'],
    story_answer: '海底',
  },
  {
    level: 'SRC300',
    character: '神',
    word: '神仙',
    sentence: '神仙会法术。',
    meaning_question: '"神"在这里的意思是什么？',
    options: ['超自然的存在', '普通人', '动物'],
    answer: '超自然的存在',
    story_text: '神仙帮了穷人，给他变出了一间房子。',
    story_question: '神仙帮了谁？',
    story_options: ['穷人', '国王', '妖怪'],
    story_answer: '穷人',
  },
  {
    level: 'SRC300',
    character: '家',
    word: '回家',
    sentence: '我回家了。',
    meaning_question: '"家"是什么？',
    options: ['住的地方', '学校', '公园'],
    answer: '住的地方',
    story_text: '放学了，小红开开心心地回家。',
    story_question: '小红放学后做什么？',
    story_options: ['回家', '去公园', '去商店'],
    story_answer: '回家',
  },
  {
    level: 'SRC300',
    character: '门',
    word: '打开门',
    sentence: '请关上门。',
    meaning_question: '"门"是什么？',
    options: ['出入口', '窗户', '桌子'],
    answer: '出入口',
    story_text: '有人敲门，妈妈打开门一看，是奶奶来了！',
    story_question: '谁来了？',
    story_options: ['奶奶', '老师', '同学'],
    story_answer: '奶奶',
  },
  {
    level: 'SRC300',
    character: '树',
    word: '大树',
    sentence: '大树下面很凉快。',
    meaning_question: '"树"是什么？',
    options: ['植物', '动物', '石头'],
    answer: '植物',
    story_text: '大树上有一个鸟窝，里面有三只小鸟。',
    story_question: '鸟窝里有什么？',
    story_options: ['三只小鸟', '三颗蛋', '三朵花'],
    story_answer: '三只小鸟',
  },
  {
    level: 'SRC300',
    character: '花',
    word: '花园',
    sentence: '花园里很漂亮。',
    meaning_question: '"花"是什么？',
    options: ['植物开的部分', '动物', '石头'],
    answer: '植物开的部分',
    story_text: '花园里的花开了，有红色的，有黄色的，真漂亮！',
    story_question: '花是什么颜色的？',
    story_options: ['红色和黄色', '蓝色', '黑色'],
    story_answer: '红色和黄色',
  },
  {
    level: 'SRC300',
    character: '河',
    word: '小河',
    sentence: '小河的水很清。',
    meaning_question: '"河"是什么？',
    options: ['流动的水', '山', '路'],
    answer: '流动的水',
    story_text: '小河里有好多鱼，孩子们在河边钓鱼。',
    story_question: '孩子们在做什么？',
    story_options: ['钓鱼', '游泳', '唱歌'],
    story_answer: '钓鱼',
  },
  {
    level: 'SRC300',
    character: '海',
    word: '大海',
    sentence: '大海很蓝。',
    meaning_question: '"海"是什么？',
    options: ['很大很大的水', '小河', '湖'],
    answer: '很大很大的水',
    story_text: '大海里有鲸鱼，鲸鱼是最大的动物。',
    story_question: '大海里有什么？',
    story_options: ['鲸鱼', '老虎', '猴子'],
    story_answer: '鲸鱼',
  },
  {
    level: 'SRC300',
    character: '爱',
    word: '喜欢',
    sentence: '我爱妈妈。',
    meaning_question: '"爱"的意思是什么？',
    options: ['很喜欢', '讨厌', '不关心'],
    answer: '很喜欢',
    story_text: '妈妈爱孩子，每天给他做好吃的饭。',
    story_question: '妈妈怎么爱孩子？',
    story_options: ['做好吃的饭', '买玩具', '讲故事'],
    story_answer: '做好吃的饭',
  },
  {
    level: 'SRC300',
    character: '怕',
    word: '害怕',
    sentence: '我害怕黑暗。',
    meaning_question: '"怕"的意思是什么？',
    options: ['恐惧', '高兴', '生气'],
    answer: '恐惧',
    story_text: '小兔子害怕大灰狼，躲在了树洞里。',
    story_question: '小兔子害怕什么？',
    story_options: ['大灰狼', '小鸟', '蝴蝶'],
    story_answer: '大灰狼',
  },
  {
    level: 'SRC300',
    character: '朋',
    word: '朋友',
    sentence: '你是我的好朋友。',
    meaning_question: '"朋友"是什么意思？',
    options: ['亲近的人', '陌生人', '敌人'],
    answer: '亲近的人',
    story_text: '两个好朋友一起去旅行，路上互相帮助。',
    story_question: '好朋友路上做什么？',
    story_options: ['互相帮助', '吵架', '各走各的'],
    story_answer: '互相帮助',
  },
  {
    level: 'SRC300',
    character: '师',
    word: '老师',
    sentence: '老师教我们读书。',
    meaning_question: '"老师"是什么？',
    options: ['教知识的人', '医生', '警察'],
    answer: '教知识的人',
    story_text: '老师带同学们去花园观察花朵。',
    story_question: '老师带同学们去哪里？',
    story_options: ['花园', '图书馆', '商店'],
    story_answer: '花园',
  },
  {
    level: 'SRC300',
    character: '爸',
    word: '爸爸',
    sentence: '爸爸在看书。',
    meaning_question: '"爸爸"是什么？',
    options: ['父亲', '母亲', '老师'],
    answer: '父亲',
    story_text: '爸爸带我去公园玩，我们一起放风筝。',
    story_question: '爸爸和我在做什么？',
    story_options: ['放风筝', '钓鱼', '跑步'],
    story_answer: '放风筝',
  },
  {
    level: 'SRC300',
    character: '妈',
    word: '妈妈',
    sentence: '妈妈做饭很好吃。',
    meaning_question: '"妈妈"是什么？',
    options: ['母亲', '父亲', '老师'],
    answer: '母亲',
    story_text: '妈妈给我做了一件新衣服，穿上真好看！',
    story_question: '妈妈做了什么？',
    story_options: ['新衣服', '新鞋子', '新书包'],
    story_answer: '新衣服',
  },
  {
    level: 'SRC300',
    character: '国',
    word: '国王',
    sentence: '国王住在城堡里。',
    meaning_question: '"国王"是什么？',
    options: ['国家的领导人', '普通人', '老师'],
    answer: '国家的领导人',
    story_text: '国王把宝物藏在了城堡的密室里，用钥匙锁上门。',
    story_question: '国王用什么锁门？',
    story_options: ['钥匙', '石头', '绳子'],
    story_answer: '钥匙',
  },
  {
    level: 'SRC300',
    character: '英',
    word: '英雄',
    sentence: '他是大英雄。',
    meaning_question: '"英雄"是什么？',
    options: ['勇敢伟大的人', '普通人', '坏人'],
    answer: '勇敢伟大的人',
    story_text: '英雄打败了妖怪，救出了村民。',
    story_question: '英雄救出了谁？',
    story_options: ['村民', '国王', '妖怪'],
    story_answer: '村民',
  },
  {
    level: 'SRC300',
    character: '学',
    word: '学校',
    sentence: '我在学校上学。',
    meaning_question: '"学校"是什么？',
    options: ['学习的地方', '吃饭的地方', '睡觉的地方'],
    answer: '学习的地方',
    story_text: '学校里有很多同学，大家一起学习，一起玩。',
    story_question: '学校里有什么？',
    story_options: ['很多同学', '很多动物', '很多花'],
    story_answer: '很多同学',
  },
  {
    level: 'SRC300',
    character: '城',
    word: '城堡',
    sentence: '城堡很漂亮。',
    meaning_question: '"城堡"是什么？',
    options: ['大的建筑', '小房子', '桥'],
    answer: '大的建筑',
    story_text: '城堡里住着公主，城堡外面有大花园。',
    story_question: '城堡外面有什么？',
    story_options: ['大花园', '大海', '沙漠'],
    story_answer: '大花园',
  },
  {
    level: 'SRC300',
    character: '打',
    word: '打开',
    sentence: '请打开书。',
    meaning_question: '"打开"的意思是什么？',
    options: ['把关着的东西开起来', '关上', '扔掉'],
    answer: '把关着的东西开起来',
    story_text: '小明打开门，看见外面下雪了！',
    story_question: '小明打开门看见什么？',
    story_options: ['下雪了', '出太阳了', '下雨了'],
    story_answer: '下雪了',
  },
  {
    level: 'SRC300',
    character: '变',
    word: '变成',
    sentence: '毛毛虫变成蝴蝶。',
    meaning_question: '"变成"的意思是什么？',
    options: ['改变成为', '保持不变', '消失'],
    answer: '改变成为',
    story_text: '孙悟空变成了一只小鸟，飞上了天空。',
    story_question: '孙悟空变成了什么？',
    story_options: ['小鸟', '大象', '鱼'],
    story_answer: '小鸟',
  },
  {
    level: 'SRC300',
    character: '开',
    word: '开始',
    sentence: '比赛开始了。',
    meaning_question: '"开始"的意思是什么？',
    options: ['起动', '结束', '停止'],
    answer: '起动',
    story_text: '上课铃响了，老师开始讲课。',
    story_question: '什么响了？',
    story_options: ['上课铃', '闹钟', '电话'],
    story_answer: '上课铃',
  },
  {
    level: 'SRC300',
    character: '完',
    word: '完成',
    sentence: '我完成了作业。',
    meaning_question: '"完成"的意思是什么？',
    options: ['做完了', '刚开始', '没做'],
    answer: '做完了',
    story_text: '小明完成了任务，得到了一颗星星。',
    story_question: '小明得到了什么？',
    story_options: ['一颗星星', '一个苹果', '一本书'],
    story_answer: '一颗星星',
  },
];

// 300字库完整字表 - 用于"逐字测试"模式
// 来源：阅读高频字300字库
export const CHAR_LIST_300: string[] = ['人', '我', '你', '他', '她', '它', '大', '小', '多', '少', '高', '低', '长', '短', '好', '坏', '新', '旧', '上', '下', '左', '右', '前', '后', '中', '里', '外', '天', '地', '日', '月', '山', '水', '火', '风', '云', '雨', '东', '西', '南', '北', '一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '百', '千', '万', '来', '去', '回', '进', '出', '开', '关', '有', '没', '是', '不', '会', '能', '要', '想', '给', '把', '和', '在', '从', '到', '这', '那', '谁', '呢', '吗', '吧', '看', '听', '说', '问', '叫', '喊', '笑', '哭', '吃', '喝', '睡', '醒', '坐', '站', '走', '跑', '跳', '飞', '拿', '找', '追', '抓', '推', '拉', '扔', '打', '帮', '救', '藏', '躲', '变', '等', '跟', '学', '教', '做', '爱', '神', '仙', '龙', '猴', '妖', '怪', '魔', '鬼', '鸟', '马', '狗', '猫', '兔', '狼', '家', '门', '窗', '房', '路', '桥', '树', '花', '草', '河', '海', '湖', '城', '村', '塔', '床', '桌', '椅', '灯', '墙', '累', '困', '饿', '冷', '热', '啊', '呀', '哇', '哦', '啦', '嘿', '哈'];

// 300字库完整词表 - 用于"逐字测试"词汇部分
export const WORD_LIST_300: string[] = ['什么', '哪里', '看见', '发现', '听见', '想到', '知道', '记得', '忘记', '打开', '关上', '带走', '回来', '离开', '经过', '变成', '使用', '开始', '继续', '停下', '决定', '试试', '准备', '完成', '保护', '相信', '喜欢', '讨厌', '害怕', '担心', '希望', '孩子', '男孩', '女孩', '朋友', '伙伴', '老师', '同学', '爸爸', '妈妈', '爷爷', '奶奶', '国王', '公主', '王子', '英雄', '师父', '徒弟', '巨人', '小偷', '客人', '主人', '队长', '村长', '国民', '百姓', '山洞', '森林', '学校', '教室', '图书馆', '商店', '市场', '花园', '城堡', '房间', '石头', '天空', '太阳', '月亮', '星星', '云彩', '大海', '高山', '沙漠', '草地', '高兴', '开心', '快乐', '难过', '生气', '紧张', '惊讶', '奇怪', '兴奋', '失望', '勇敢', '聪明', '认真', '善良', '友好', '骄傲', '着急', '舒服', '安全', '为什么', '怎么办', '真的吗', '太好了', '不好了', '快点', '等等', '小心', '别怕', '没关系', '原来', '就是', '当然', '也许', '可能', '一定', '不会', '可以', '不行', '谢谢', '走路', '跑步', '跳起来', '飞走', '说话', '大笑', '哭了', '打开门', '关上门', '找到', '追上', '帮助', '出发', '旅行', '寻找', '宝物', '秘密', '地图', '钥匙', '危险', '怪物', '妖怪', '神仙', '龙王', '魔法', '法术', '任务', '挑战', '胜利', '失败'];

// 导出所有题库
export function getQuestionsByLevel(level: Level): Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] {
  switch (level) {
    case 'SRC300':
      return questionsSRC300;
    case 'SRC500':
      // V1 使用 SRC300 题库的变体
      return questionsSRC300;
    case 'SRC800':
      // V1 使用 SRC300 题库的变体
      return questionsSRC300;
    default:
      return questionsSRC300;
  }
}

export function getAllQuestions(): Omit<QuestionItem, 'id' | 'created_at' | 'updated_at'>[] {
  return [...questionsSRC300];
}
